### ISSUE TITLE
Maven or Gradle Set Problem

### ISSUE THREAD

**Issue by deluser8** [secure-software-engineering/FlowDroid#103]
Hi everyone,
Can we update maven repos? The lastest version is 2.0.0. But if there are some new version will be helpful to us.

**Comment by StevenArzt** [comment]
For the development snapshots, you can have a look here: http://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/. For the releases, we have http://soot-build.cs.uni-paderborn.de/nexus/repository/soot-release/. These repositories contain the versions up to 2.7.

**Comment by deluser8** [comment]
Thank you very much~
