### ISSUE TITLE
Can't parse RIFL file

### ISSUE THREAD

**Issue by AmrAshraf** [secure-software-engineering/FlowDroid#11]
Hello there,

When i tried to put `rifl.rifl` (change the extinction of `rifl.xml` come from `SuSi`) instead of `SourcesAndSinks.txt` it throws exception in `RIFLParser.java` showing that : 
`stateStack.peek()` and `stateStack.pop()` throws because the stack is empty.

After that i made a condition to bypass those conditions, but there aren't any sources and sinks definitions found in the `RIFLDocument` after parsing it with the bypass.

I am tracing it and if i found a something i will tell you, but i need only to make sure that the problem not coming from SuSi file if you tried it before. 

Thanks.

**Comment by AmrAshraf** [comment]
Hello @StevenArzt , i solved the problem with RIFL parsing and other dependencies and also serialize the category with the sources and sinks in the output XML file.
Should i ask for a pull to develop or master branch?
Thanks.

**Comment by StevenArzt** [comment]
Thanks a lot! Please submit a pull request to the develop branch.
