### ISSUE TITLE
Cannot execute 2.70

### ISSUE THREAD

**Issue by FoelliX** [secure-software-engineering/FlowDroid#112]
Hi!

Nice to see a new version of FlowDroid being released again.
Sadly I cannot execute 2.70 as before (2.61). I just downloaded https://github.com/secure-software-engineering/FlowDroid/releases/download/v2.7/soot-infoflow-cmd-jar-with-dependencies.jar
and tried the following:
2.70: NullPointerException
```
fpauck@vm-ma-fpauck:~/tools/FlowDroid/270$ java -jar soot-infoflow-cmd-jar-with-dependencies.jar -a DirectLeak1.apk -p /media/sf_sdks/platforms/ -s SourcesAndSinks.txt
[main] INFO soot.jimple.infoflow.cmd.MainClass - Analyzing app /home/fpauck/tools/FlowDroid/270/DirectLeak1.apk (1 of 1)...
The data flow analysis has failed. Error message: null
java.lang.NullPointerException
        at soot.jimple.infoflow.cmd.MainClass.run(MainClass.java:315)
        at soot.jimple.infoflow.cmd.MainClass.main(MainClass.java:231)
```
2.61: working fine
```
fpauck@vm-ma-fpauck:~/tools/FlowDroid/261$ java -jar soot-infoflow-cmd-jar-with-dependencies.jar -a DirectLeak1.apk -p /media/sf_sdks/platforms/ -s SourcesAndSinks.txt
[main] INFO soot.jimple.infoflow.taintWrappers.EasyTaintWrapper - Loaded wrapper entries for 90 classes and 12 exclusions.
[main] INFO soot.jimple.infoflow.android.SetupApplication - Initializing Soot...
...
[main] INFO soot.jimple.infoflow.android.SetupApplication - Found 1 leaks
```

Possible bug:
I have been looking into the source code and found:
```
String outputFileStr = config.getAnalysisFileConfig().getOutputFile();
			File outputFile = null;
if (outputFileStr != null && !outputFileStr.isEmpty()) {
```
outputFile stays null here in case of my launch parameters, i guess.
Thus line 315 is reached:
`outputFile.exists() && outputFile.isDirectory()`
where exists() is called on a null object.

**Comment by StevenArzt** [comment]
This is indeed a bug. Apparently, we did not catch the bug during testing, because the tests are mass tests, Thanks for reporting.
