### ISSUE TITLE
How to track sinks only?

### ISSUE THREAD

**Issue by kneep** [secure-software-engineering/FlowDroid#116]
Hello. Is it possible to track sinks only? That means I would like to know all the calls to certain methods no matter what the input is. For example, I just want to know who are changing the secure settings but don't care what values these settings are changing to.
Here's the sources and sinks file. But it seems not work.
```
<android.provider.Settings$Secure: boolean putFloat(android.content.ContentResolver,java.lang.String,float)> -> _SINK_
<android.provider.Settings$Secure: boolean putInt(android.content.ContentResolver,java.lang.String,int)> -> _SINK_
<android.provider.Settings$Secure: boolean putLong(android.content.ContentResolver,java.lang.String,long)> -> _SINK_
<android.provider.Settings$Secure: boolean putString(android.content.ContentResolver,java.lang.String,java.lang.String)> -> _SINK_
```

**Comment by StevenArzt** [comment]
FlowDroid is a data flow tracker, i.e., it tracks data flow between sources and sinks. Only finding where a certain method is called is not a data flow problem. You can do this using the Soot and FlowDroid APIs. You first need to construct a callgraph, then iterate over all units in all methods in all classes, and check the interprocedural control flow graph (ICFG) for the callees of interest.

This roughly works like this: Create an instance of the ```SetupApplication``` class and call ```constructCallgraph()```. Then create an instance of the ```InfoflowCFG``` class. Afterwards, iterate over all classes in your Scene (```Scene.v().getClasses()```), iterate over all methods in each class (```SootClass.getMethods()```), get the units for each method (```SootMethod.getActiveBody().getUnits()```), and for each unit, check (```InfoflowCFG.getCalleesOfCallAt()```).
