### ISSUE TITLE
Purpose of android.jar as input

### ISSUE THREAD

**Issue by AmrAshraf** [secure-software-engineering/FlowDroid#12]
Hello There,

I am wondering why it is required to provide android plateform directory which contains android.jar, As sources and sinks are already provided by the txt, xml, or RIFL file.

Thanks.

**Comment by StevenArzt** [comment]
The Android JAR files are used for obtaining method signatures and type hierarchies in addition to many smaller aspects (e.g., access modifiers). The source and sink definitions alone are not sufficient.
