### ISSUE TITLE
Detailed question about callback analyzing

### ISSUE THREAD

**Issue by mikesxf** [secure-software-engineering/FlowDroid#128]
Hi! Recently I am reading the source of flowdroid but find something I can't understand.
In the part of finding callback methods, `DefaultCallbackAnalyzer.java`, it has a inner class `MyReachableMethods` and its annotation is `helper class that computes reachable methods only from a given set of starting methods`.
However, I can't understand why we should find callback registrations in these reachable methods rather than in a given set of starting methods?Maybe I miss something important?
Thanks!

**Comment by StevenArzt** [comment]
This code collects callbacks for a given Android component (e.g. Activity) inside the app. The callback collection is an iterative process. For each component, we start with the lifecycle methods. We then check which methods are reachable from there, and in each reachable method, we check whether a new callback is registered. This gives us a set of callback classes that are apparently used from inside the current component. We then re-compute our callgraph to extend it with the callback handlers inside the model for the parent component. This extension, in turn, might make new methods reachable from the methods associated with the component thus far. In these new methods, we also have to check for new callback registrations. We iterate the process until there are no more changes.

While this approach may seem tedius, we don't have much of a choice here. For each callback, we need to know in which components it is used. Usage is based on registration. Therefore, we must know which callbacks are registered (transitively) by each component.

**Comment by mikesxf** [comment]
Thank you for your detailed explanation! It helps a lot. But I'm sorry I still have some questions.
When I follow the code step by step, I find that many reachable methods belong to other class rather than this component, e.g., the reachable method of one Activity's lifecycle methods is `a()` and its class `class a` has some widgets too (like TextView). In `a()`, it registers a listener `class b` for the textview. As a result, flowdroid relates `class b` to the Activity.
I'm not sure whether the result is OK in this situation. As I understand, if I relate a class (listener) to Activity, it is possible that callback method in the class (like `OnClick()`) will be triggered when I interact with the Activity. However, it seems not the case in the example above.

**Comment by StevenArzt** [comment]
I'm not sure I fully understand your question. If some activity A registers a listener, it doesn't matter whether this registration happens directly inside the class A or not. It is perfectly ok to instantiate some other class, e.g., inside ```A.onCreate()```, call a method in that other class, have the callback registered there. The question is rather: What is the component the user interacts with when he invoked the callback by, e.g., clicking on the button? The technical details on how the button was registered inside the activity don't matter for the user's interaction with the app.

**Comment by mikesxf** [comment]
Thank you for your answer. I understand your words and I think it solves the question of this issue. I'm still struggling to understand and use flowdroid, I think I'd better open new issue later when I meet other questions. Thanks again!

**Comment by mikesxf** [comment]
Oh, another little question. Is there any reference about the process of taint analysis in source code? It is a little hard for me to understand it. Thanks!

**Comment by StevenArzt** [comment]
For a description of how FlowDroid works, please have a look at my PhD thesis: https://bodden.de/pubs/phd-arzt.pdf
