### ISSUE TITLE
How to get and save Jimple files？

### ISSUE THREAD

**Issue by android4studies** [secure-software-engineering/FlowDroid#129]
Hi, I have a question about FlowDroid. 

Q: How to save Jimple files when analyze an apk with FlowDroid?

Details:
I want to get the Jimple files of a specific apk.

The process of FlowDroid is: apk-->Jimple-->control flow graph-->dataflow analysis-->taint paths, I use FlowDroid to analyze this apk and I can get the taint paths. 
but when I used soot to get Jimple files of this apk, I got some error informations.

So can FlowDroid save Jimple files during analysing, if yes, how to get it? 

Plus:
error informations as figure:
![2019-03-06 21 46 09](https://user-images.githubusercontent.com/29922203/53885837-a1a93a00-4059-11e9-83a7-14692eea6f89.png)

Convert Dalvik to Jimple using Soot with this command:
`java  -jar  sootclasses-trunk-jar-with-dependencies.jar  -allow-phantom-refs  -process-multiple-dex  -w  -src-prec  apk  -f  jimple  -d  <JimplefilesPath>  -android-jars  <ANDROIDJAR>  -process-dir <apkPath>`

Thanks for your reply :)

**Comment by StevenArzt** [comment]
FlowDroid is built on Soot. Therefore, you should get the same Jimple files out of Soot that are also internally processed by FlowDroid. For your convenience, I have just added a new command-line option to FlowDroid so that you can also have FlowDroid write out the Jimple files without having to start Soot. The new option is ``-wj" or ``--writejimplefiles```.

**Comment by android4studies** [comment]
Thanks for your generosity. And May I ask another question that when can I use this command with 
 FlowDroid?

**Comment by StevenArzt** [comment]
I have checked in the code. If you build the "develop" branch on your own, you can already use the new command-line option.

**Comment by android4studies** [comment]
OK. Thanks.

**Comment by SnoopyTlion** [comment]
You can use
```config.setWriteOutputFiles(true);```
in your code to tell flowDroid to write jimple file in your sootoutput directory.
