### ISSUE TITLE
FlowDroid 2.7.1 Maven build with tests failing

### ISSUE THREAD

**Issue by Andreas237** [secure-software-engineering/FlowDroid#136]
Hi team,
I am unable to build **FlowDroid 2.7.1** using Maven with tests.  The output of the build is in [MavenBuild_withTests_Errors.txt](https://github.com/secure-software-engineering/FlowDroid/files/2979501/MavenBuild_withTests_Errors.txt).

Digging into the **surefire** reports it appears that FlowDroid is trying to reference APKs `StrongUpdate1.apk`, `SimpleAliasing1.apk`, and `FlowSensitivity1.apk` ([see here](https://github.com/secure-software-engineering/FlowDroid/blob/master/soot-infoflow-android/test/soot/jimple/infoflow/android/test/droidBench/AliasingTests.java)) in the **DroidBench** project that don't exist in the latest version, [DroidBench 2.0](https://github.com/secure-software-engineering/DroidBench/tree/master/apk/AndroidSpecific).

I am submitting this issue to FlowDroid since the reference is in FlowDroid code.  Please let me know if you need further information.

The surefire reports for failed tests are:
[soot.jimple.infoflow.android.test.droidBench.AndroidSpecificTests.txt](https://github.com/secure-software-engineering/FlowDroid/files/2979556/soot.jimple.infoflow.android.test.droidBench.AndroidSpecificTests.txt)
[soot.jimple.infoflow.android.test.droidBench.ArrayAndListTests.txt](https://github.com/secure-software-engineering/FlowDroid/files/2979557/soot.jimple.infoflow.android.test.droidBench.ArrayAndListTests.txt)
[soot.jimple.infoflow.android.test.droidBench.CallbackTests.txt](https://github.com/secure-software-engineering/FlowDroid/files/2979558/soot.jimple.infoflow.android.test.droidBench.CallbackTests.txt)
[soot.jimple.infoflow.android.test.droidBench.EmulatorDetectionTests.txt](https://github.com/secure-software-engineering/FlowDroid/files/2979559/soot.jimple.infoflow.android.test.droidBench.EmulatorDetectionTests.txt)
[soot.jimple.infoflow.android.test.droidBench.FieldAndObjectSensitivityTests.txt](https://github.com/secure-software-engineering/FlowDroid/files/2979560/soot.jimple.infoflow.android.test.droidBench.FieldAndObjectSensitivityTests.txt)
[soot.jimple.infoflow.android.test.droidBench.GeneralJavaTests.txt](https://github.com/secure-software-engineering/FlowDroid/files/2979561/soot.jimple.infoflow.android.test.droidBench.GeneralJavaTests.txt)
[soot.jimple.infoflow.android.test.droidBench.ImplicitFlowTests.txt](https://github.com/secure-software-engineering/FlowDroid/files/2979562/soot.jimple.infoflow.android.test.droidBench.ImplicitFlowTests.txt)
[soot.jimple.infoflow.android.test.droidBench.InterComponentCommunicationTests.txt](https://github.com/secure-software-engineering/FlowDroid/files/2979563/soot.jimple.infoflow.android.test.droidBench.InterComponentCommunicationTests.txt)
[soot.jimple.infoflow.android.test.droidBench.LifecycleTests.txt](https://github.com/secure-software-engineering/FlowDroid/files/2979564/soot.jimple.infoflow.android.test.droidBench.LifecycleTests.txt)
[soot.jimple.infoflow.android.test.droidBench.ReflectionTests.txt](https://github.com/secure-software-engineering/FlowDroid/files/2979565/soot.jimple.infoflow.android.test.droidBench.ReflectionTests.txt)
[soot.jimple.infoflow.android.test.droidBench.ThreadingTests.txt](https://github.com/secure-software-engineering/FlowDroid/files/2979566/soot.jimple.infoflow.android.test.droidBench.ThreadingTests.txt)
[soot.jimple.infoflow.android.test.insecureBank.InsecureBankTests.txt](https://github.com/secure-software-engineering/FlowDroid/files/2979567/soot.jimple.infoflow.android.test.insecureBank.InsecureBankTests.txt)
[soot.jimple.infoflow.android.test.manifest.ProcessManifestTest.txt](https://github.com/secure-software-engineering/FlowDroid/files/2979568/soot.jimple.infoflow.android.test.manifest.ProcessManifestTest.txt)
[soot.jimple.infoflow.android.test.otherAPKs.OtherAPKTests.txt](https://github.com/secure-software-engineering/FlowDroid/files/2979569/soot.jimple.infoflow.android.test.otherAPKs.OtherAPKTests.txt)
[soot.jimple.infoflow.android.test.sourceToSinks.SourceToSinksTest.txt](https://github.com/secure-software-engineering/FlowDroid/files/2979570/soot.jimple.infoflow.android.test.sourceToSinks.SourceToSinksTest.txt)
[soot.jimple.infoflow.android.test.xmlParser.SigToAndroidMethodTest.txt](https://github.com/secure-software-engineering/FlowDroid/files/2979571/soot.jimple.infoflow.android.test.xmlParser.SigToAndroidMethodTest.txt)
[soot.jimple.infoflow.android.test.xmlParser.XmlParserTest.txt](https://github.com/secure-software-engineering/FlowDroid/files/2979572/soot.jimple.infoflow.android.test.xmlParser.XmlParserTest.txt)

**Comment by zhanghan177** [comment]
Have you checked out the `develop` branch of DroidBench?

**Comment by Andreas237** [comment]
That worked, thank you!
