### ISSUE TITLE
Error running soot-infoflow-android after Maven Build

### ISSUE THREAD

**Issue by Andreas237** [secure-software-engineering/FlowDroid#137]
I'm sorry I have been unable to solve this on my own, so I'm posting here.

I built the tool using Maven, including all the tests.  My problem arises when trying to use the `.jar` in the same manner as the CMD tool.  

The command I am using is:
```
  java -jar <path to FlowDroid>/soot-infoflow-android-classes.jar soot.jimple.infoflow.android.TestApps.Test \
  -a <APK path> \
  -p <path to Android SDK>/platforms \
  -s <path to sources and sinks>/SourcesAndSinks.txt
  ```

The error is:
```
Error: Could not find or load main class soot.jimple.infoflow.android.TestApps.Test
Caused by: java.lang.ClassNotFoundException: soot.jimple.infoflow.android.TestApps.Test
``` 

I see that `soot.jimple.infoflow.android.TestApps.Test` was an parameter in the CMD tool so I tried running the above command with and without it and received the same error.  

If there is documentation I missed please do send it.

Thank you in advance for guiding this rookie.

**Comment by StevenArzt** [comment]
You need to run the ```soot-infoflow-cmd-jar-with-dependencies.jar``` file. This file contains the full FlowDroid build wih all required dependencies. The JAR you tried to use only contains the Android-specific components, but not, e.g., the command-line tool.

**Comment by Andreas237** [comment]
Thank you Steven.
