### ISSUE TITLE
Flowdroid - Callgraph generation for a simple app with API 28

### ISSUE THREAD

**Issue by Mithu22** [secure-software-engineering/FlowDroid#139]
@StevenArzt 
Hi 

I am trying to build a callgraph for an APK that was created with Android version 28. I am able to generate call graphs for the Droidbench test apps (which have a targetSdk of 17). I have a minSdk of 22 and a targetSdk of 28 for my APK. The same code invoked gives me an error. I set parameters to merge multiple dex files and also to set_multiple_dex to true. I am using Flowdroid 2.7. 

Please find below, the code used and the error message . Is there anything wrong with the configuration or anything additionally that needs to be done to get this to work with API 28 ?

Code -
        //Config
        InfoflowAndroidConfiguration config = new InfoflowAndroidConfiguration();
        config.getAnalysisFileConfig().setAndroidPlatformDir(androidJarPath);
        config.getAnalysisFileConfig().setTargetAPKFile(apkPath);
        config.setMergeDexFiles(true);
        soot.options.Options.v().set_whole_program(true);
        soot.options.Options.v().set_allow_phantom_refs(true);
        soot.options.Options.v().set_prepend_classpath(true);
        soot.options.Options.v().set_force_android_jar(androidJarPath);
        soot.options.Options.v().set_src_prec(Options.src_prec_apk);
        soot.options.Options.v().set_android_jars(androidJarPath);
        soot.options.Options.v().force_overwrite();
        soot.options.Options.v().set_process_dir(Collections.singletonList(apkPath));
        soot.options.Options.v().set_output_format(Options.output_format_dex);
        soot.options.Options.v().set_force_overwrite(true);
        soot.options.Options.v().set_process_multiple_dex(true);
        Scene.v().addBasicClass("java.io.PrintStream", SootClass.SIGNATURES);
        Scene.v().loadNecessaryClasses();        config.setSootIntegrationMode(InfoflowAndroidConfiguration.SootIntegrationMode.UseExistingInstance);
        IInfoflowConfig sootConfig = new SootConfigForAndroid();
        sootConfig.setSootOptions(soot.options.Options.v(), config);
        SetupApplication analyzer = new SetupApplication(config); 
        analyzer.setSootConfig(sootConfig);
        analyzer.constructCallgraph();

Error - 
/usr/lib/jvm/jdk-11.0.2/bin/java -javaagent:/home/maithreyi/Downloads/idea-IU-183.4284.148/lib/idea_rt.jar=42621:/home/maithreyi/Downloads/idea-IU-183.4284.148/bin -Dfile.encoding=UTF-8 -classpath /home/maithreyi/Downloads/cfg/CfgTest/production/CfgTest:/home/maithreyi/FlowDroid/soot-infoflow-cmd-jar-with-dependencies.jar Cfg /home/maithreyi/Desktop/jadx_apk/test_apk/CFGTest1.apk /home/maithreyi/FlowDroid/android.jar
[main] INFO soot.jimple.infoflow.android.SetupApplication - ARSC file parsing took 0.04858075 seconds
[main] WARN soot.jimple.infoflow.android.SetupApplication - No entry points
Exception in thread "main" java.lang.RuntimeException: No call graph present in Scene. Maybe you want Whole Program mode (-w).
	at soot.Scene.getCallGraph(Scene.java:1369)
	at Cfg.main(Cfg.java:81)

Process finished with exit code 1

Any help will be greatly appreciated. Also, any pointers on additional documentation on the configuration of Flowdroid will be appreciated.

**Comment by minkylee** [comment]
invoke anayzer.runInfoflow(xx) before analyzer.constructCallgraph();

**Comment by StevenArzt** [comment]
Why do you initialize the Soot instance on your own? Unless you have a very specific use case, that shouldn't be necessary. Have you tried the following reduced approach?

```
InfoflowAndroidConfiguration config = new InfoflowAndroidConfiguration();
config.getAnalysisFileConfig().setAndroidPlatformDir(androidJarPath);
config.getAnalysisFileConfig().setTargetAPKFile(apkPath);
config.setMergeDexFiles(true);

SetupApplication analyzer = new SetupApplication(config);
analyzer.constructCallgraph();
```

**Comment by Mithu22** [comment]
@StevenArzt , Hi Steven, There is no change with the reduced approach either. I built a simple Android application using Android Studio (API 28) and built an APK and ran Flowdroid from the command line on that APK. It still gives a "No entry points" error with the -d (merge dex) option enabled. Is there something else with building the APK that can make a difference?

**Comment by StevenArzt** [comment]
Can you please provide the APK? It seems to work with all APKs that I can build. I therefore need your file to further debug this issue.

**Comment by BushraAloraini** [comment]
Similar issue here, the analyzer works fine with older apks. However,  when analyzing apks with api 28,  it gives "No entry points". The attached file is a sample apk that has the issue.


[app-release.apk.zip](https://github.com/secure-software-engineering/FlowDroid/files/3315787/app-release.apk.zip)

**Comment by dusby** [comment]
Hello @StevenArzt,

I experienced the same issue this morning with a "zitmo" like android app and I think I found the problem, look for example the activity declaration in @BushraAloraini app : 

```
<activity android:label="@string/app_name" android:name="com.google.sample.echo.MainActivity" android:screenOrientation="portrait">
    <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
    </intent-filter>
</activity>
```

We can see that the activity is named "com.google.sample.echo.MainActivity"

Now take a look at checkAndAddComponent method in Flowdroid : 

```
private void checkAndAddComponent(Set<String> entryPoints, AXmlNode node) {
    AXmlAttribute<?> attrEnabled = node.getAttribute("enabled");
    if (attrEnabled == null || !attrEnabled.getValue().equals(Boolean.FALSE)) {
        AXmlAttribute<?> attr = node.getAttribute("name");
            if (attr != null) {
                String className = expandClassName((String) attr.getValue());
                if (!SystemClassHandler.isClassInSystemPackage(className))
                    entryPoints.add(className);
            } else {
                // This component does not have a name, so this might be
                // obfuscated malware. We apply a heuristic.
                for (Entry<String, AXmlAttribute<?>> a : node.getAttributes().entrySet()) {
                    AXmlAttribute<?> attrValue = a.getValue();
                    if (attrValue != null) {
                        String attrValueName = attrValue.getName();
                        if ((attrValueName == null || attrValueName.isEmpty())
                                && attrValue.getType() == AxmlVisitor.TYPE_STRING) {
                            String name = (String) attrValue.getValue();
                            if (isValidComponentName(name)) {
                                String expandedName = expandClassName(name);
                                if (!SystemClassHandler.isClassInSystemPackage(expandedName))
                                    entryPoints.add(expandedName);
                            }
                        }
                    }
                }
            }
        }
    }
```

The piece of code we are interested in is this one : 

```
AXmlAttribute<?> attr = node.getAttribute("name");
    if (attr != null) {
        String className = expandClassName((String) attr.getValue());
        if (!SystemClassHandler.isClassInSystemPackage(className))
            entryPoints.add(className);
    }
```

attr get the value : name="com.google.sample.echo.MainActivity", so it is not null, then className get the value : com.google.sample.echo.MainActivity
Then a check is performed on this name, this is the code of the check : 

```
public static boolean isClassInSystemPackage(String className) {
        return className.startsWith("android.") || className.startsWith("java.") || className.startsWith("javax.")
                || className.startsWith("sun.") || className.startsWith("org.omg.")
                || className.startsWith("org.w3c.dom.") || className.startsWith("com.google.")
                || className.startsWith("com.android.");
}
```

We clearly see the problem here, it is assumed that if the className startsWith "com.google." it is a system class, so the class is not added as an entrypoint. But in this case, the className startsWith "com.google." but is not a system class.
I experienced the same issue with a class named "com.android.security.xxx", therefore I ended up without callgraph.
I think the heuristic is not precise enough.

**Comment by StevenArzt** [comment]
Let me close this issue as a duplicate auf #171
