### ISSUE TITLE
question about soot.jimple.infoflow.handlers.TaintPropagationHandler

### ISSUE THREAD

**Issue by singleboat** [secure-software-engineering/FlowDroid#140]
I find this interface when I'm trying to record some taint intermediate result except the sink point. Is this interface developed for users to write their own code, which has ability to process each tainted local or method found by flowdroid?

**Comment by StevenArzt** [comment]
Yes, this interface indeed allows user code to process taint abstractions during the data flow analysis.

**Comment by singleboat** [comment]
Thanks, it helps a lot.
