### ISSUE TITLE
How to install FlowDroid?

### ISSUE THREAD

**Issue by r-zh** [secure-software-engineering/FlowDroid#142]
Hi,

I have cloned the git to my PC and operate the command
```
mvn -DskipTests install
```
But there is the error. Do you know why it failed?

![image](https://user-images.githubusercontent.com/7058710/55586400-d7901b80-56f6-11e9-859c-9f547f2d6349.png)

**Comment by StevenArzt** [comment]
That was indeed a bug in the POM files for Maven. I have just committed a fix, along with some other improvements.

**Comment by r-zh** [comment]
Hi,
Sorry for bothering. Has this problem been solved yet?

**Comment by StevenArzt** [comment]
Please use the most recent development branch and try compiling again. It should now work. If there's still a problem, please let me know.

**Comment by r-zh** [comment]
Yeah, it works! Thank you so much.

For others who have same problems, operate the command as follows in order.
```
git clone ....Flowdorid.git
git checkout origin/develop
mvn -DskipTests install
```
![image](https://user-images.githubusercontent.com/7058710/55979326-e8451200-5c5f-11e9-9b1e-5523c018420b.png)

**Comment by Pokmona1** [comment]
hola ejhecuto los pasos pero me sale este mensaje 
![image](https://github.com/user-attachments/assets/5dac2338-d647-4dd9-b48b-fbc15da9f40c)
y no crea el flowdroid.jar
![image](https://github.com/user-attachments/assets/6ec16cce-a045-4ed5-804d-c14520a57933)
