### ISSUE TITLE
How to print the callback function detail?

### ISSUE THREAD

**Issue by r-zh** [secure-software-engineering/FlowDroid#143]
Hi,

I operated this command to use Flowdroid. 
```
java -jar soot-infoflow-cmd-jar-with-dependencies.jar -a kiss.apk -p ./ 
     -s ../FlowDroid/soot-infoflow-android/SourcesAndSinks.txt
```
There is one INFO: 
```
Callback analysis terminated normally
```
and 
```
1 callback method
```
![image](https://user-images.githubusercontent.com/7058710/55651909-091ceb80-57b8-11e9-991a-fc000d3f7b1e.png)

My goal is to **find this callback function, but I do not know how to print its detail**, including the name, class and variables. Could you please tell me how to do that? Should I modify the command?

In addition, do you **have any documents to explain the usage of these JARs**? I just know the soot-infoflow-cmd-jar-with-dependencies.jar, which is explained in Readme.MD.

![image](https://user-images.githubusercontent.com/7058710/55652067-79c40800-57b8-11e9-89b2-8ec23c05ab0c.png)

**Comment by StevenArzt** [comment]
The callback analyuer is implemented in the ```DefaultCallbackAnalyzer``` class. If you want to print out the callback functions it has discovered, I'd suggest to modify the ```SetupApplication``` class and access ```this.callbackMethods``` at the end of the ```calculateCallbackMethods()``` method.

The JAR files you mention contain different builds of FlowDroid components. The file structure is as follows: For each individual component inside FlowDroid, we have the "-classes.jar" file, which contains the compiled code for just that individual component. We then have JARs that contain the JavaDoc help files and the source code for just that component. The "with-dependencies" JARs contain not only the individual components, but also the dependencies. That allows us to directly run FlowDroid with only one JAR on the classpath.

**Comment by r-zh** [comment]
@StevenArzt Yeah, thanks for your reply. I have accessed ```this.callbackMethods```. However, when I print it out.
```
System.out.println( this.callbackMethods.values());
```
 It just shows the class and method name, like:
```
[<de.testApp.sourcetosink4.MainActivity: void onCreate(android.os.Bundle)>]
```
I need to print the Jimple code **inside** of the function```onCreate()``` Could you please give me any ideas? Thank you so much!

**Comment by StevenArzt** [comment]
If you need the complete code of the ```onCreate()``` method, you can simply call ```getActiveBody()``` on the ```SootMethod``` object.
