### ISSUE TITLE
How to figure out the data flow from SINK to SOURCE?

### ISSUE THREAD

**Issue by Anttree1563** [secure-software-engineering/FlowDroid#146]
Currently, FlowDroid provides the information about data flow from source to sink,
which means the privacy leaks.
However I'm actually interested with the data flow from SINK TO SOURCE either, but I don't know the way how to get them.
Is there any way to get flows from sink to source?

**Comment by StevenArzt** [comment]
I'm not exactly sure what your use case is, because data is passed from source to sink and not vice versa. However, you can just reverse the mapping in your own code, i.e., iterate over the source-to-sink mapping and just fill the data into a map with reverse semantics.
