### ISSUE TITLE
Particular Source not found

### ISSUE THREAD

**Issue by swyyws** [secure-software-engineering/FlowDroid#160]
Hi, i have an issue with the a source not being detected by FlowDroid.

`ContentResolver ce = getContentResolver();`
`String andid = Secure.getString(ce, Secure.ANDROID_ID);`
`Log.w("Test", "AndroidId = " + andid);`

This is what i have in a simple application and below is how i specify the source in the SourcesAndSinks file. 

`<android.provider.Settings.Secure: java.lang.String getString(android.content.ContentResolver,java.lang.String)> android.permission.READ_PHONE_STATE -> _SOURCE_`
`<android.provider.Settings.Secure: java.lang.String getString(android.content.ContentResolver,java.lang.String)> ->_SOURCE_`

So i was wondering why FlowDroid seems to be unable to detect this particular leak? Appreciate any help given!

**Comment by StevenArzt** [comment]
Your source definition is wrong, because ```Secure``` is an inner class inside ```Settings```. The correct definition is as follows:

```
<android.provider.Settings$Secure: java.lang.String getString(android.content.ContentResolver,java.lang.String)> ->_SOURCE_
```
