### ISSUE TITLE
Unable to access jarfile soot-infoflow-cmd/target/soot-infoflow-cmd-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by AliMasarweh** [secure-software-engineering/FlowDroid#189]
Hi!

When I try to run on the command line
` java -jar soot-infoflow-cmd/target/soot-infoflow-cmd-jar-with-dependencies.jar`
`Error: Unable to access jarfile soot-infoflow-cmd/target/soot-infoflow-cmd-jar-with-dependencies.jar`

I cloned the repository of the pre-built JAR files, and they don't have the target folder in the soot-infoflow-cmd folder,
Is there any way to obtain the target folder?
Should I build the JAR files with maven?

Thanks!

**Comment by StevenArzt** [comment]
You should run a Maven build using ``mvn package``. This command should build all required projects and also take care of the dependencies.
