### ISSUE TITLE
Miss a leak in my test apk

### ISSUE THREAD

**Issue by heyzhangz** [secure-software-engineering/FlowDroid#191]
hi, 
I write a simple demo apk to test FlowDriod, however it can only report the first leak successfully, but miss the second one.
Here is the key code :
```java
byte[] senbytes = outbytes.toByteArray();   //source
String senstr = new String(senbytes);
Log.i("leak1", "a" + new String(senbytes)); //sink1
Log.i("leak2", "a" + senstr);               //sink2
```
Interestingly, it can report 2 leaks successfully by swapping the Line 3 and Line 4.

To find the reason, I print out the associated jimple code as follow :
```
$r8 = virtualinvoke $r2.<java.io.ByteArrayOutputStream: byte[] toByteArray()>();
$r11 = new java.lang.String;
$r4 = $r11;
specialinvoke $r11.<java.lang.String: void <init>(byte[])>($r8);
r14 = new java.lang.StringBuilder;
$r10 = r14;
specialinvoke r14.<java.lang.StringBuilder: void <init>()>();
virtualinvoke $r10.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("a");
r15 = new java.lang.String;
specialinvoke r15.<java.lang.String: void <init>(byte[])>($r8);
virtualinvoke $r10.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r15);
$r11 = virtualinvoke $r10.<java.lang.StringBuilder: java.lang.String toString()>();
staticinvoke <android.util.Log: int i(java.lang.String,java.lang.String)>("leak1", $r11);
r14 = new java.lang.StringBuilder;
$r10 = r14;
specialinvoke r14.<java.lang.StringBuilder: void <init>()>();
virtualinvoke $r10.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("a");
virtualinvoke $r10.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>($r4);
$r4 = virtualinvoke $r10.<java.lang.StringBuilder: java.lang.String toString()>();
staticinvoke <android.util.Log: int i(java.lang.String,java.lang.String)>("leak2", $r4);
```
And I find a possible reason is that the assignment is before initialization between line 2 and line 4 . Due to it, the value `$r4` isn't tainted by `$r8`, and then Flowdroid will miss the leak when calling sink method `android.util.Log(String, String)` with `$r4` as a parameter.
```
$r8 = virtualinvoke $r2.<java.io.ByteArrayOutputStream: byte[] toByteArray()>();
$r11 = new java.lang.String;
$r4 = $r11;      //assignment before initialization
specialinvoke $r11.<java.lang.String: void <init>(byte[])>($r8);
 ...
specialinvoke r14.<java.lang.StringBuilder: void <init>()>();
virtualinvoke $r10.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("a");
virtualinvoke $r10.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>($r4);
$r4 = virtualinvoke $r10.<java.lang.StringBuilder: java.lang.String toString()>();
staticinvoke <android.util.Log: int i(java.lang.String,java.lang.String)>("leak2", $r4);
```
How can I do to solve this problem? Thank you.

**Comment by StevenArzt** [comment]
Thanks for investigating this issue. The reason is fairly simple: Since sztrings

**Comment by StevenArzt** [comment]
Thanks for investigating this issue. The reason is actually fairly interesting. Since strings are immutable objects in Java, we expected them to never have aliases, which is normally a fair assumption. You can never modify a string, so even if someone holds a reference to a string, no operation can change that string or some contents of it afterwards. You will always end up with a new string. We therefore disabled alias analysis for strings to improve performance.

You actually found the only case in which this assumption falls short of reality. In case the string object has not been initialized, the contents of the string can actually be modified after creating an alias by invoking the constructor. We didn't think of that. I'll commit a patch.

**Comment by StevenArzt** [comment]
@heyzhangz Can you please try again with the new version? If that doesn't help, can you please provide a minimal working example? My examples don't seem to generate such interesting Jimple code and manually reading in Jimple has challenges on its own.

**Comment by heyzhangz** [comment]
@StevenArzt Unfortunately, I get the same result with the new version.
Here is my example :
my test apk :
[https://github.com/heyzhangz/TestApp/tree/master/testcase](https://github.com/heyzhangz/TestApp/tree/master/testcase)
and the apk's source code :
[https://github.com/heyzhangz/TestApp/tree/master/app/src/main/java/com/mine/testapp](https://github.com/heyzhangz/TestApp/tree/master/app/src/main/java/com/mine/testapp)

**Comment by StevenArzt** [comment]
Your APK now works for me:

```
The sink virtualinvoke $r3.<java.io.DataOutputStream: void write(byte[])>($r8) in method <com.mine.testapp.MainActivity$1: void onClick(android.view.View)> was called with values from the following sources:
- $r4 = virtualinvoke $r7.<android.telephony.TelephonyManager: java.lang.String getDeviceId()>() in method <com.mine.testapp.MainActivity$1: void onClick(android.view.View)>
The sink staticinvoke <android.util.Log: int i(java.lang.String,java.lang.String)>("leak1", $r11) in method <com.mine.testapp.MainActivity$1: void onClick(android.view.View)> was called with values from the following sources:
- $r4 = virtualinvoke $r7.<android.telephony.TelephonyManager: java.lang.String getDeviceId()>() in method <com.mine.testapp.MainActivity$1: void onClick(android.view.View)>
The sink staticinvoke <android.util.Log: int i(java.lang.String,java.lang.String)>("leak2", $r4) in method <com.mine.testapp.MainActivity$1: void onClick(android.view.View)> was called with values from the following sources:
- $r4 = virtualinvoke $r7.<android.telephony.TelephonyManager: java.lang.String getDeviceId()>() in method <com.mine.testapp.MainActivity$1: void onClick(android.view.View)>
```

@heyzhangz Can you please double-check?

**Comment by heyzhangz** [comment]
@StevenArzt It also works for me.
Thank you so much.
