### ISSUE TITLE
Question about using both StubDroid and easy taint wrappers

### ISSUE THREAD

**Issue by zjbthomas** [secure-software-engineering/FlowDroid#196]
Hi,

I noticed that StubDroid does not model all Java or Android methods, so easy taint wrappers are still necessary in some cases. Therefore, I want to mix them together.

I tried both "-tw MULTI -t /path/to/summariesManual/ /path/to/EasyTaintWrapperSource.txt" and "-tw MULTI -t /path/to/EasyTaintWrapperSource.txt /path/to/summariesManual/", but it seems like only the first argument after -t is in effect.

Could you please provide a way to correctly use these two at the same time? Thank you in advance!

**Comment by StevenArzt** [comment]
You only need to specify ``-tw multi`` once. Then provide multiple arguments ``-t`` with the respective files. Maybe the parser got confused with the multiple taint wrapper types in your argument list. If that doesn't solve your problem, you can set a breakpoint in method ``initializeTaintWrapper`` in class soot.jimple.infoflow.cmd.MainClass``. Maybe the software can't find the second file and therefore skips it.
