### ISSUE TITLE
Generic types

### ISSUE THREAD

**Issue by xiaodiannao** [secure-software-engineering/FlowDroid#197]
Hi everyone, thanks for this awesome project! I have a quick question regarding the SourcesAndSinks.txt file: How do I define a sink with a generic return type? So if I for example want to identify `public T load(String input)` as a sink how would I do that?

**Comment by StevenArzt** [comment]
There are no generic types in Java bytecode. Since FlowDroid reads the bytecode, you need to specify the type to which the Java compiler reduces your generic. In your example, that would most likely be ``java.lang.Object``. If you have some ``T extends Foo``, it would be ``Foo`` though.

**Comment by xiaodiannao** [comment]
Hi Steven, ah alright thanks a lot for your explanation everything is clear now!
