### ISSUE TITLE
Analysis was aborted & not sure if callgraph was generated

### ISSUE THREAD

**Issue by chocologurt** [secure-software-engineering/FlowDroid#2]
Hi, 

I am trying to use the command line tool to run the data flow tracker. I used the following command:
`java -jar soot-infoflow-cmd/target/soot-infoflow-cmd-jar-with-dependencies.jar -a Google_Duo_v24.0.178310191.DR24.0_RC13_apkpure.com.apk  -p /home/choco/Android/Sdk/platforms -s /home/choco/Desktop/FlowDroid/FlowDroid-2.5.1/soot-infoflow-android/SourcesAndSinks.txt -o /home/choco/Desktop/FlowDroid/FlowDroid-2.5.1/analysis_output/output2.xml`

However, I received a message saying that " For information on where the call graph may be incomplete, use the verbose option to the cg phase " and that an error stating that " [main] ERROR soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - No sources found, aborting analysis"

The attachment below is the full output when I executed the command:
[output.docx](https://github.com/secure-software-engineering/FlowDroid/files/1645134/output.docx)

I am currently using this APK as a test. In my Android Platforms directory, it has _android-23_ and _android-27_ folders. I have also used the default "SourcesAndSinks.txt" file that can be found in the "soot-infoflow-android" folder. 
I'm not sure if the callgraph was generated but since the analysis was aborted, I presume the callgraph was not generated and the XML file that contains the DataFlowResults is empty too. 

Really appreciate any feedback that I can get :)

**Comment by chocologurt** [comment]
@StevenArzt

**Comment by StevenArzt** [comment]
The warning about the potentially incomplete callgraph is nothing to worry about. Soot reports this warning in some cases in which it has to approximate. Your real problem is that no sources were found. That means that no statement in the APK file that you analyze matches any source definition in your SourcesAndSinks.txt file. You need to look into the APK to find out whether this is actually the case or whether we have a bug there.

**Comment by chocologurt** [comment]
Alright! Thank you for your advice and I will try configuring the SourcesAndSinks.txt file
