### ISSUE TITLE
Sink definition question

### ISSUE THREAD

**Issue by xiaodiannao** [secure-software-engineering/FlowDroid#205]
Hi all

Another question just popped up regarding Flowdroid sink detection and the SourcesAndSinks.txt file. Flowdroid detects java.io.BufferedWriter: 
void write(java.lang.String) as a "Sink Statemenet". The curious thing is though, this method is not defined as a sink in the SourcesAndSinks.txt file. (java.io.Writer is in the SourcesAndSinks.txt file) 
How is this possible?

Best regards

**Comment by StevenArzt** [comment]
FlowDroid automatically check the hierarchy of source and sink methods. A ``BufferedWriter`` is derived from ``Writer``, therefore ``Writer`` also matches it.

**Comment by xiaodiannao** [comment]
Alright ok I wasn't sure if that was the case, thanks for your quick reply Steven, take care!
