### ISSUE TITLE
Usage of IccTA in Flowdroid

### ISSUE THREAD

**Issue by JordanSamhi** [secure-software-engineering/FlowDroid#219]
Hello,

Sorry in advance for the long post, but I am having a hard time using Flowdroid with IccTA with the command line and as a library.
The problem is that it does not detect simple leaks, I even tried it with some of the Droidbench ICC apps.
Of course I used IC3 to generate the ICC model (first I retargeted the app with Dare) and it has been correctly constructed (see [com.example.apptest_1.txt](https://github.com/secure-software-engineering/FlowDroid/files/3961152/com.example.apptest_1.txt)).

I will describe an app I developped to test with two leaks: 

First leak in the `onCreate()` method of the MainActivity :
```java
String imei = null;
TelephonyManager telephonyManager = (TelephonyManager)getSystemService(Context.TELEPHONY_SERVICE);
if(ContextCompat.checkSelfPermission(this, Manifest.permission.READ_PHONE_STATE) == PackageManager.PERMISSION_GRANTED){
    imei = telephonyManager.getDeviceId();
}
SmsManager.getDefault().sendTextMessage("sms",null,imei,null,null);    
```
This leak is detected when I do not use the -im option of Flowdroid.

Then, when I use this option with the previously generated ICC model, this leak is no longer detected (even if it has nothing to do with ICC).

Second leak from MainActivity to Activity1:

- `onCreate()` method of MainActivity : 

```java
String imei = null;
TelephonyManager telephonyManager = (TelephonyManager)getSystemService(Context.TELEPHONY_SERVICE);
if(ContextCompat.checkSelfPermission(this, Manifest.permission.READ_PHONE_STATE) == PackageManager.PERMISSION_GRANTED){
    imei = telephonyManager.getDeviceId();
}
Intent i = new Intent(this, activity1.class);
i.putExtra("phoneId",imei);
startActivity(i);
```

- `onStart()` method of Activity1: 

```java
protected void onStart(){
    String s = this.getIntent().getStringExtra("phoneId");
    SmsManager.getDefault().sendTextMessage("sms",null,s,null,null);
}
```

This second leak is not detected either, though it should.

As I said I used some Droidbench apps that have been developped for ICC tests but I have the same problem, no leak detected.

I even tried it as a library by using the `ifac.getIccConfig().setIccModel()` method. Then I compared the body of the `onCreate()` method of MainActivity with the same body without calling the `ifac.getIccConfig().setIccModel()` method. 
There was no difference, I mean that what is described in IccTA paper did not appear (connection of components with new methods (IpcSc, redirect0, getIntent, etc..)).
As if nothing is happening, though I use an ICCmodel.
Like what @StevenArzt is saying in #155 does not happen : 
"FlowDroid uses this data to extend its callgraph such that the call to startActivity() also triggers the lifecycle dummy main method of the target component. In other words, FlowDroid transforms ICC calls into normal method calls to then run its normal data flow propagation over an interprocedural control flow graph (ICFG)."

So, whether something is wrong or I am misusing the tool.

Command lines I used:
```bash
./dare-1.1.0-linux/dare -d [resultsPath] [appName]
java -jar ic3-0.2.0-jar-with-dependencies.jar -input [retargeted app folder] -apkormanifest [appName] -cp [pathToAndroid.jar] -protobuf [pathToOutput]
java -jar soot-infoflow-cmd-jar-with-dependencies.jar -a [appName] -p [pathToAndroidPlatofrms] -s SourcesAndSinks.txt -im [pathToIC3Results]
```

You can find [here](https://github.com/secure-software-engineering/FlowDroid/files/3961201/results.txt) the output of all the commands I launched.

Thank you in advance !

PS: I used the latest available release of Flowdroid: 2.7.1 and I also tried with the one I built from the sources of the develop branch.

**Comment by yokotayokota** [comment]
Hello

I am having a hard time using Flowdroid2.9 with IccTA with the command line.
I downloaded dare and ic3-0.2.0.jar, but they don't work on my ubuntu 20.04.3 LTS.
The reference site http://siis.cse.psu.edu/ has disappeared.

Is there any other way to analyse an apk using Flowdroid with IccTA?
I saw the archive of soot mailing list but I could not find related subjects.
I am not familiar with Flowdroid or soot, so I would be grateful if you could tell me basic instructions.
Or where should I ask this question?

Thank you in advance. 
I look forward to hearing from you.

**Comment by JordanSamhi** [comment]
Resolved in latest version of Flowdroid.
