### ISSUE TITLE
Dump all tainted items

### ISSUE THREAD

**Issue by traceprobe** [secure-software-engineering/FlowDroid#236]
Dear Sir,
I am using FlowDroid to analyze data leaks. But was wondering is it possible to print all tainted items (statements and methods) out during analysis?

I am asking this question since, in my case, it's difficult to define a fixed set of sink APIs, but i still want to see the data dependencies.

Thanks,
Bob

**Comment by traceprobe** [comment]
I went through the related classes of SetupApplication, but have no clue. Could you advise me to the related packages and classes in the project? Thank you!!!

**Comment by traceprobe** [comment]
have to reopen the issue. 

I thought it could be done by the TaintPropagationHandler, but it seems only the source API related statements are printed in notifyFlowIn and notifyFlowOut methods.

**Comment by X-czh** [comment]
I guess [this issue](https://github.com/secure-software-engineering/FlowDroid/issues/111) is relevant here.
