### ISSUE TITLE
Maven failed for soot-infoflow-android

### ISSUE THREAD

**Issue by E0HYL** [secure-software-engineering/FlowDroid#237]
> [ERROR] Failed to execute goal on project soot-infoflow-android: Could not resolve dependenc for project de.tud.sse:soot-infoflow-android:jar:2.7.3-SNAPSHOT: Failed to collect dependens at ca.mcgill.sable:axmlprinter:jar:2016-07-27

It seems that the following two sites can't be visited:
https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/
https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-release/

Any solution for this? Thank you in advance.

**Comment by E0HYL** [comment]
I did the following two steps, and it worked for me.
- use the jar file from [here](https://mvnrepository.com/artifact/com.android/AXMLPrinter/1.0.0), and modify the `dependency`:

> 
		<dependency>
			<groupId>com.google.protobuf</groupId>
			<artifactId>protobuf-java</artifactId>
			<version>3.4.0</version>
		</dependency>


- modify the `repositories` like this:
> 	<repositories>
		<repository>
			<id>soot-snapshot</id>
			<name>Soot snapshot server</name>
			<url>http://dev.91xmy.com/nexus/content/repositories/releases/</url>
		</repository>
		
	</repositories>

Build Success. Hope there would be no problems in the future.😄

**Comment by gokul-bhoomi** [comment]
How do we do this @E0HYL? Please help
