### ISSUE TITLE
Missing dependency on maven

### ISSUE THREAD

**Issue by ufarooq** [secure-software-engineering/FlowDroid#276]
Hi @ericbodden @johspaeth @nguyenLisa ,

FlowDroid (Artifact: soot-infoflow) 2.7.1 depends on heros version 1.0.1-SNAPSHOT, which has been **removed** from snapshot repository. Currently, snapshot contains only versions 1.2.0,.. 1.2.3
For reference, available versions metadeta. 

```
<versions>
<version>1.2.0-SNAPSHOT</version>
<version>1.2.2-SNAPSHOT</version>
<version>1.2.3-SNAPSHOT</version>
</versions>
```
Dependency for soot-infoflow 

```
<!--  Built by http://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/  -->
<dependency>
<groupId>heros</groupId>
<artifactId>heros</artifactId>
<version>1.0.1-SNAPSHOT</version>
</dependency>
```

Bests,
Umar

**Comment by StevenArzt** [comment]
FlowDroid 2.7.1 is outdated. The current version (see develop branch) uses Heros 1.2.1. The last release version 2.8 should also be fine.

**Comment by ufarooq** [comment]
@StevenArzt Thanks for the quick response. I would really appreciate if version 2.7.1 dependency (heros snapshot) become available. Upgrading to new version is not desirable in my situation (sorry!!).

**Comment by ufarooq** [comment]
I am able to resolve by downgrading to version 2.7.
