### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by wozuo** [secure-software-engineering/FlowDroid#277]
Hi all

Is there a way to intercept all logging output before it is printed to stdout? I use the latest v2.8 flowdroid JAR which includes all dependencies and import the necessary classes to run a taint analysis in my own Java project (which works great).

I tried adding log4j-1.2.17 to my dependencies and creating my own appender by extending `AppenderSkeleton` and creating a log4j.properties file:

```
log4j.rootLogger=DEBUG, MYAPPENDER, console

log4j.appender.MYAPPENDER =example.MyAppender
log4j.appender.console=org.apache.log4j.ConsoleAppender
```

But to no effect. My appender is ignored and the logs are printed to the console somehow. Is there a log4j configuration in Flowdroid which overrides my configuration or what am I doing wrong?

Thanks a lot and best regards

**Comment by wozuo** [comment]
Alright I solved the issue I was having by adding the following dependency in my project (where I'm importing Flowdroid):

```
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-log4j12</artifactId>
    <version>1.7.5</version>
</dependency>
```

And removing the `slf4j-simple` dependency from the `soot-infoflow-cmd` pom file and the `log4j` dependency from `secure-software-engineering/FlowDroid/pom.xml`.

Is there a maven repo with an up-to-date version for Flowdroid btw @StevenArzt ?

**Comment by StevenArzt** [comment]
We don't have FlowDroid on Maven Central or any other repository at the moment. Internally, we use our own Maven repository based on Nexus.

**Comment by wozuo** [comment]
I saw the Nexus one, but the newest version doesn't seem to be on there. Is the recommended way to just use the cmd with dependencies JAR to use FlowDroid as a library?
