### ISSUE TITLE
infoflow constructor's first parameter

### ISSUE THREAD

**Issue by gygl09** [secure-software-engineering/FlowDroid#28]
In SetupApplication.java (Line: 1447):
```
final String androidJar = config.getAnalysisFileConfig().getTargetAPKFile();
InPlaceInfoflow info = new InPlaceInfoflow(androidJar, forceAndroidJar, cfgFactory);
```

Infoflow constructor's first parameter should be android.jar, right?
But in the code, the apk path, which is provided by "getTargetAPKFile()", is imported.
Is the code right?

**Comment by StevenArzt** [comment]
Which version of FlowDroid are you using? In the current development branch, the problem doesn't seem to be there. Can you try again with the development version?

**Comment by gygl09** [comment]
It should be the newest (dev) version. Can you check the link:
https://github.com/secure-software-engineering/FlowDroid/blob/master/soot-infoflow-android/src/soot/jimple/infoflow/android/SetupApplication.java#L1447

**Comment by StevenArzt** [comment]
The development version is on the "develop" branch. The "master" branch contains the last stable release version.

**Comment by gygl09** [comment]
ohh, I see. Thank you!

**Comment by gygl09** [comment]
It seems the problem is still there:
https://github.com/secure-software-engineering/FlowDroid/blob/develop/soot-infoflow-android/src/soot/jimple/infoflow/android/SetupApplication.java#L1497

But does that first parameter matter?

**Comment by StevenArzt** [comment]
I see. It doesn't make any difference, because the SetupApplication class already creates the Soot instance and uses Infoflow in-place. Therefore, we could have passed an arbitrary string. For avoiding any confusion, I have changed the line nevertheless.
