### ISSUE TITLE
Fragments using FragmentPagerAdapter

### ISSUE THREAD

**Issue by dah-fari7009** [secure-software-engineering/FlowDroid#283]
Hi,
 I am trying to build a model of an Android application using the callgraph provided by soot. For each screen of the application, I need to identify sub-elements such as fragments or drawers. I noticed that some of the fragment classes are missing from my model and this corresponds to activities where Fragments are added using FragmentPagerAdapter in this fashion:

![image](https://user-images.githubusercontent.com/35702512/95029842-142c3280-0660-11eb-8dad-e76c5c788e34.png)

Please correct me if I am wrong, but it seems like fragments added with this type of adapter are not handled. Is there any chance you could provide me with some pointers on how to proceed to add support for this, when identifying the fragment classes.

I am using soot-infoflow-android v2.7.1 and running on an application from the RecDroid dataset: https://github.com/AndroidTestBugReport/ReCDroid/blob/master/Evaluation%20Result/apks/8.AnyMemo-v10.10.1_debug.apk

**Comment by maryammsd** [comment]
@dah-fari7009 : Did you find any solution for it? Can you share it if there is any?

**Comment by StevenArzt** [comment]
I have added some support for such cases and the fragments in your APK should now be detected.

**Comment by maryammsd** [comment]
Thanks @StevenArzt , I will build it and make it a try :)

**Comment by maryammsd** [comment]
It is working now :)
