### ISSUE TITLE
call graph and entry points are empty

### ISSUE THREAD

**Issue by liveanddie09** [secure-software-engineering/FlowDroid#30]
Hi,

I am trying to run Flowdroid, but I always get empty callgraph and entry points. Could you help me check the reason? The following is my main code.

```
SetupApplication setup_app = new SetupApplication(android_jars, apk_path);
File taintWrapperFile = new File(TAINT_WRAPPER);
setup_app.setTaintWrapper(new EasyTaintWrapper(taintWrapperFile));

InfoflowAndroidConfiguration config = setup_app.getConfig();
config.getAnalysisFileConfig().setSourceSinkFile(SOURCE_SINK_FILE);

setup_app.constructCallgraph();
setup_app.printEntrypoints();
```

The test app can be accessed using the link: https://www.dropbox.com/s/o70aqlftdyk2a2s/google_ads_banner_example.apk

Best wishes

**Comment by liveanddie09** [comment]
I guess many google ads classes are excluded from analysis. Can I know how to add them back?
------------
another problem is that it seems the edges of call graph are removed during analysis. Base on Infoflow.runanalysis()'s log:
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Callgraph has 16 edges
there are 16 edges. However, when I print the edges after  setup_app.constructCallgraph(), the edge number becomes zero.
I tried several benchmark apps, and got the same results:
such as Threading/AsyncTask1.apk, Callbacks/Button1.apk

**Comment by liveanddie09** [comment]
For the call graph problem, it seems I must use addPreprocessor() to register some handlers to deal with call graphs. It this right?

**Comment by gygl09** [comment]
To read call graph, it is better to register a ResultsAvailableHandler instance.
The only problem is why the entry points starting with "com.google" can not be detected?

**Comment by liveanddie09** [comment]
For the entry points, there are something wrong with the function "checkAndAddComponent()". I am still checking its code.

**Comment by liveanddie09** [comment]
SystemClassHandler.isClassInSystemPackage() thinks "com.google" is a system package name. Do you think it is possible to remove it, since this may influence analysis on google own apps?

**Comment by liveanddie09** [comment]
It may be better to make the private method "parseAppResources()" as a protected/public method, so that we can customize event points.

**Comment by StevenArzt** [comment]
I made the method protected instead or private. Does this resolve the problem or is there anything else you need?
