### ISSUE TITLE
Can FlowDroid point to a gradle project?

### ISSUE THREAD

**Issue by qwacsawd** [secure-software-engineering/FlowDroid#301]
Hi there,

Is there an option to allow flowdroid to point to a gradle project instead of running it off Android Studio as a library?

For example setting the path of an Android Project such that the CFG generated is in java instead of setting it to an APK file so that the output is in java instead of smali?

**Comment by StevenArzt** [comment]
FlowDroid uses Maven as a build system, not Gradle, although it would be perfectly possible to create a Gradle build file for the project. Feel free to contibute one.

FlowDroid is a Java program. We use Eclipse for development, but IntelliJ should work as well, just as any other Java development environment. Android Studio is intended to build Android apps, not Java programs. It might work to import FlowDroid into Android Studio, but I wouldn't recommend it.

The data flow analysis is built on top of Soot, and therefore works on the Jimple IR. We don't use smali, and we don't use Java source code for analysis. In fact, we don't have a working frontend for Java source code at the moment, so you can only analze APKs and Java bytecode (class files).
