### ISSUE TITLE
Soot Taint Analysis for apk files

### ISSUE THREAD

**Issue by qwacsawd** [secure-software-engineering/FlowDroid#302]
Hi there,

I have a sample code
```
package com.example.myapplication;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Intent intent = getIntent();
        Uri data = intent.getData();


        if(data.getScheme().startsWith("test")) {
            sendBroadcast(intent);
        } else {
            sendBroadcast(intent);
        }
    }
}
```

With my source and sink text file as:
```
<android.content.Intent: android.content.Intent getIntent(java.lang.String)> -> _SOURCE_
<android.content.Context: void sendBroadcast(android.content.Intent)> -> _SINK_
```

However, when I run soot via command line, `java -jar D:\Downloads\Android\soot-infoflow-cmd.jar -a D:\Downloads\Android\app-debug.apk -p C:\Users\null\AppData\Local\Android\Sdk\platforms -s D:\Downloads\Android\SourceandSinks.txt -o soot.xml -i ALL`, I get no results. Did I miss out something?

**Comment by StevenArzt** [comment]
Are you sure that your source and sink file name is correct? Our default file has a different spelling, it's called ``SourcesAndSinks.txt`` (you are missing a letter).

**Comment by qwacsawd** [comment]
HI @StevenArzt, even with the correct source and sink file, the data flow analysis is still unable to find the leaks. The logs did show that it was able to identify the source and sink that I have specified:
```
...
[main] INFO soot.jimple.infoflow.android.source.AccessPathBasedSourceSinkManager - Created a SourceSinkManager with 1 sources, 1 sinks, and 68 callback methods.
...
[main] WARN soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - No results found.
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Data flow solver took 1 seconds. Maximum memory consumption: 265 MB
[main] INFO soot.jimple.infoflow.android.SetupApplication - Found 0 leaks
```

**Comment by StevenArzt** [comment]
Wereyou able to find a solution? If so, please comment for other users that may encounter similar problems.

**Comment by qwacsawd** [comment]
Sadly no...

**Comment by YaphetsH** [comment]
> Sadly no...

The source taint can access getIntent call site with service or boardcast context ,but for activity,the method signature of getIntent is from current context (e.g  <com.example.myapplication.MainActivity : android.content.Intent getIntent(java.lang.String)> )
