### ISSUE TITLE
ICC leak in FlowDroid

### ISSUE THREAD

**Issue by negara** [secure-software-engineering/FlowDroid#316]
Hello, 
My understanding is that current version of FlowDroid handles inter component flows as well (includes IccTA). 
Therefore, I expect to see a leak for the example below:

1. In SourceSink.txt file I included only these two line:
`<android.telephony.TelephonyManager: java.lang.String getDeviceId()> android.permission.READ_PHONE_STATE -> _SOURCE_
sendTextMessage(java.lang.String,java.lang.String,java.lang.String,android.app.PendingIntent,android.app.PendingIntent)> android.permission.SEND_SMS -> _SINK_ `

2. My app has two activities A and B.

```

public class A extends Activity {
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        String taintedString = telephonyManager.getDeviceId();
        Intent taintedIntent = new Intent(this, B.class);
        taintedIntent.setAction(taintedString);
        startActivity(taintedIntent); 
    }
}

public class B extends Activity {
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        SmsManager sms = SmsManager.getDefault();
        sms.sendTextMessage("99999999", null, getIntent().getAction(), null, null);  
    }
}
```

However, I cannot see the leak in the results.
Could you please explain why FlowDroid is not able to find such leaks?

**Comment by negara** [comment]
Solved, needed the ic3 model info with -im option

**Comment by won0-kim** [comment]
Hi, I have the same issue. how do you make a model?
