### ISSUE TITLE
FlowDroid missing leak between OkHttp methods

### ISSUE THREAD

**Issue by schmidii** [secure-software-engineering/FlowDroid#334]
Hello,

I am currently stuck with a strange problem.  My Android code is the following: 

```java
...
Response response = client.newCall(request).execute();
data = response.body().string();

RequestBody postBody = new FormBody.Builder()
        .add("leak", data)
        .build();

request = new Request.Builder()
        .post(postBody)
        .url("https://www.sink.com/")
        .build();

response = client.newCall(request).execute();
...
```

I have specified `<okhttp3.Call: okhttp3.Response execute()>` as source and sink (both), unfortunately no leak gets reported (tested with FlowDroid 2.8 EasyTaintWrapper and SummaryTaintWrapper).  I also tried to add the okhttp functions to the easy taint wrapper but without success, for the summary taint wrapper I first generated the summaries with stubdroid.

Nevertheless, FlowDroid finds a leak from `<okhttp3.ResponseBody: java.lang.String string()> -> _SOURCE_` to `<okhttp3.Call: okhttp3.Response execute()> -> _SINK_`, but not from the previous statement `<okhttp3.Response: okhttp3.ResponseBody body()>` to the `execute` method...

Someone knows what the problem might be, I am looking forward to your answer.

**Comment by StevenArzt** [comment]
What do your added lines for the ``EasyTaintWrapper`` look like? I assume your reduced test case ("Nevertheless...") was run with the ``EasyTaintWrapper`` and not StubDroid, right?

It's quite odd that the complex part of the data flow works (all the nested request objects), but a flow from a tainted body over a simple call to ``string()`` gets lost. Did you step through the ``EasyTaintWrapper`` in the debugger? The rules in there are fairly simple: If the signature of the method that receives the taint is in the taint wrapper configuration file, and a parameter or the base object is tainted, the return value gets tainted as well. This somehow seems to work, else the reduced test case wouldn't have worked either. There is simply no good reason why the simple rule should not work for ``string()`` alone.

Are you sure that your source definition in the reduced example is correct? The ``-> _SOURCE_`` seems to be missing there. That doesn't answer the question why the "big" test doesn't work, but it might sens us down the wrong road in debugging.

**Comment by schmidii** [comment]
Thank you for the quick reply. After stepping through the `EasyTaintWrapper` I found the problem, in the end I had forgotten to include the `okhttp3.*` package in the easy taint wrapper. But still I am confused why the subpart from `<okhttp3.ResponseBody: java.lang.String string()>` onward is working without including the package, but the two statements `<okhttp3.ResponseBody: java.lang.String string()>` and  `<okhttp3.Response: okhttp3.ResponseBody body()> ` are not.

**Comment by StevenArzt** [comment]
That's strange indeed. If the complete test case works as well, please close the issue.
