### ISSUE TITLE
phantom class java.util.concurrent.Future was set to not a interface

### ISSUE THREAD

**Issue by KB5201314** [secure-software-engineering/FlowDroid#340]
I am currently running the code on the develop branch (commit id: 0d84b911013bb5123b5e1879d34f10f63f501912), and encountered some problems: The introduction of `ClassMethodSummaries` broke something:

The class `java.util.concurrent.Future` is actually a `interface`, but the `isInterface` field was set to `false`:

![image](https://user-images.githubusercontent.com/14936301/115889830-e20ce180-a486-11eb-9702-1db90a14a033.png)

This will cause the modifiers of this `SootClass` instance to be re-set to "not a interface":

https://github.com/secure-software-engineering/FlowDroid/blob/0d84b911013bb5123b5e1879d34f10f63f501912/soot-infoflow-cmd/src/soot/jimple/infoflow/cmd/MainClass.java#L386-L392

And this has resulted in a `RuntimeException` During taint analysis:

![image](https://user-images.githubusercontent.com/14936301/115890813-ebe31480-a487-11eb-8365-a48a7c765005.png)

**Comment by flankerhqd** [comment]
It's a taint wrapper summaries problem. There's a bug in XML parsing. I'll submit a patch for that.

**Comment by StevenArzt** [comment]
That was actually a very stupid bug in the summary XML parser. I wonder why this got overlooked so long. Thanks for reporting.
