### ISSUE TITLE
Noticed that tag "activity-alias" in AndroidManifest.xml is not taken into account by ProcessManifest

### ISSUE THREAD

**Issue by LouisonGitzinger** [secure-software-engineering/FlowDroid#35]
Hi there,

I was trying to find launchable activities from the facebook.apk below : 
https://drive.google.com/open?id=1H1A03jywwOY6B61JdUHZTh-r2MNQZ-Z8
I have been surprised that ```ProcessManifest.getLaunchableActivities()``` didn't find any launchable activity.

So I had a look in the AndroidManifest.xml of the apk and i found out that the only "launchable" activity was contained in an "activity-alias" tag.

By looking to the ProcessManifest class code, I saw that only activities with the tag "activity" are taken into account.

How could we manage to solve this ? Maybe I can make a pull request but what is the best  : 
- merge alias activities with standard activities
- have two different lists, one for standard activities and one for alias activities ?

Thank you for all you've done with FlowDroid :)

**Comment by StevenArzt** [comment]
The best approach would be to model activity aliases as a separate entity type in ProcessManifest. We would then need to extend getLanchableAcitivities() to look for aliases as well. With this approach, users of the ProcessManifest class decide for themselves whether they want to treat activities and aliases alike or whether they want to have some special treatment for aliases. Furthermore, aliases have different properties than activities according to the Android documentation.

It would be great if you could prepare a pull request on this issue. In case you have any questions, feel free to contact me.

**Comment by LouisonGitzinger** [comment]
Ok, I'll prepare a pull request, and we will discuss how to concretely do that in the pull request thread :)

**Comment by StevenArzt** [comment]
Thanks a lot.

**Comment by LouisonGitzinger** [comment]
Hi Steven, 
I wrote the code for this particular issue, and I'm looking for a way to test it easily. 
How do you usually test your new `FlowDroid` code on a given apk ?

Thanks

**Comment by StevenArzt** [comment]
FlowDroid has JUnit test cases that run against DroidBench, and a set of APKs provided in the "testAPKs" folder of the soot-infoflow-android package. I'd recommend that you create a similar JUnit test for an APK that has an activity alias and check whether you can find the correct flows. The existing JUnit tests should be good examples on how this works with just a few lines of code. The abstract base class handles most of the work, you only need to provide the APK name and then call one of the provided checker methods to verify the flows.
