### ISSUE TITLE
Can FlowDroid analyse a set of jars?

### ISSUE THREAD

**Issue by 0range228** [secure-software-engineering/FlowDroid#364]
Hi everyone,

I'm new to FlowDroid , I was wondering if FlowDroid can do taint analysis for specific jar packages? Or a set of jars?

I would definitely appreciate every answer.

**Comment by StevenArzt** [comment]
If you have multiple JARs, you can just put all of them as input files (e.g., as the first parameter of ``Infoflow.computeInfoflow()``) where you separate the individual JARs with the file separator for your respective platform, e.g., a semicolon on Windows. Essentially, just concatenate the file names with the correct separator and you should be fine.

**Comment by 0range228** [comment]
Thanks a lot !
