### ISSUE TITLE
How to instrument a apk file with custom library in FlowDroid2.0?

### ISSUE THREAD

**Issue by RonaldQin** [secure-software-engineering/FlowDroid#37]
`public class InstrumentListener {
	public static SootField $flyTrace = new SootField("$flyTrace", 
			RefType.v("com.google.common.collect.LinkedHashMultimap"),
			Modifier.PUBLIC | Modifier.STATIC);
	
	public static SootField $invokeSite = new SootField("$invokeSite", IntType.v(), Modifier.PUBLIC | Modifier.STATIC);
	
	public static void main(String[] args) throws IOException, XmlPullParserException {
		String androidPlatformPath = "G:/androidsdk/platforms";
		String appPath = "G:/Program Files (x86)/MyEclipse 2016/Workspaces/JudgeUserAnalysis2/apk/JudgeUser.apk";
		String sourceAndSinksFilePath = "G:/Program Files (x86)/MyEclipse 2016/Workspaces/JudgeUserAnalysis2/lib/SourcesAndSinks.txt";
		String callBacksFilePath = "G:/Program Files (x86)/MyEclipse 2016/Workspaces/JudgeUserAnalysis2/lib/AndroidCallbacks.txt";
		
		SetupApplication app = new SetupApplication(androidPlatformPath, appPath);
		app.setCallbackFile(callBacksFilePath);
		app.runInfoflow(sourceAndSinksFilePath);
//		soot.G.reset();
		
//		Options.v().set_app(true);
		Options.v().set_java_version(Options.java_version_1_8);
		Options.v().set_src_prec(Options.src_prec_apk);
		Options.v().set_output_format(Options.output_format_jimple);
//		Options.v().set_output_format(Options.output_format_dex);
//		Options.v().set_output_dir(SourceLocator.v().getOutputDir() + "\\outApk");
		
		Options.v().set_android_jars(androidPlatformPath);
		Options.v().set_android_api_version(19);
		Options.v().set_process_dir(Collections.singletonList(appPath));
		Options.v().set_whole_program(true);
		Options.v().set_no_bodies_for_excluded(true);
		Options.v().set_allow_phantom_refs(true);
		Options.v().setPhaseOption("cg.spark", "on");
		
		SootMethod entryPoint = app.getDummyMainMethod();
		entryPoint.setName("main");
		Options.v().set_main_class(entryPoint.getDeclaringClass().getName());
		Scene.v().setEntryPoints(Collections.singletonList(entryPoint));
		Scene.v().loadNecessaryClasses();
		Scene.v().loadBasicClasses();
		Scene.v().loadDynamicClasses();
		
		Scene.v().addBasicClass("com.google.common.collect.LinkedHashMultimap", SootClass.SIGNATURES);
		Scene.v().addBasicClass("java.util.HashMap", SootClass.SIGNATURES);
		Scene.v().addBasicClass("java.util.LinkedHashMap", SootClass.SIGNATURES);
		Scene.v().addBasicClass("java.io.FileOutputStream", SootClass.SIGNATURES);
		Scene.v().addBasicClass("java.lang.Object", SootClass.SIGNATURES);
		Scene.v().addBasicClass("java.lang.Runnable", SootClass.SIGNATURES);
		Scene.v().addBasicClass("java.io.PrintStream", SootClass.SIGNATURES);
		Scene.v().addBasicClass("java.lang.Runtime", SootClass.SIGNATURES);
		Scene.v().addBasicClass("java.lang.Thread", SootClass.SIGNATURES);
		
		PackManager.v().getPack("wjtp").add(new Transform("wjtp.AddJimpleBodyLineTag", new AddJimpleBodyLineTag()));
		PackManager.v().getPack("wjap").add(new Transform("wjap.LoopAreaAnalysis", new LoopAreaAnalysis()));
		PackManager.v().getPack("wjap").add(new Transform("wjap.ConditionAreaAnalysis", new ConditionAreaAnalysis()));
		
		PackManager.v().getPack("jtp").add(new Transform("jtp.instrument1", new InstrumentListenerWithMainClassClinit()));
		PackManager.v().getPack("jtp").add(new Transform("jtp.instrument2", new InstrumentListenerWithAllMethod2()));
		
		PackManager.v().runPacks();
		
	}
}`

Like above, I instrument a apk file with $flyTrace and it's type is com.google.common.collect.LinkedHashMultimap. But report error: java.lang.RuntimeException: tried to get nonexistent method <com.google.common.collect.LinkedHashMultimap: com.google.common.collect.LinkedHashMultimap create()>

**Comment by StevenArzt** [comment]
Please be more specific about your question? Also please note that this is the FlowDroid project. Do not post general questions on Soot here. Instead, use the Soot mailing list for such questions.

**Comment by RonaldQin** [comment]
I want to use FlowDroid2.0 to instrument a .apk file. Now, I want to instrument this apk a jimple statement such as "<com.google.common.collect.LinkedHashMultimap: com.google.common.collect.LinkedHashMultimap create()>". But report error:java.lang.RuntimeException: tried to get nonexistent method above.

**Comment by StevenArzt** [comment]
I still don't understand your question, sorry.
