### ISSUE TITLE
Can a specific variable (known Local) to be a source?

### ISSUE THREAD

**Issue by cyxin577** [secure-software-engineering/FlowDroid#387]
If I already locate a variable (e.g., Local in Jimple) and want to taint from it, can I add it to the sources of Flowdroid?
Could you give me some advice? Thanks a lot.

**Comment by StevenArzt** [comment]
Yes, you can. Have a look at the ``StatementSourceSinkDefinition`` class.

**Comment by cyxin577** [comment]
Thanks for reply!
Could you please give an example to add the new source to Flowdroid? Do I need to overwrite `SetupApplication` class?

**Comment by StevenArzt** [comment]
You don't need to overwrite it, you can just use the ``SetupApplication`` class. Call ``runInfoflow`` and pass a custom implementation of an ``ISourceSinkDefinitionProvider`` that returns the ``StatementSourceSinkDefinition`` when asked for a source.

**Comment by cyxin577** [comment]
Thanks a lot for your reply!! 
Do you mean that I need to customize an implementation of  `ISourceSinkDefinitionProvider` and override its `getSource()` method, which returns a set of `StatementSourceSinkDefinition`,  and I need to use the following constructor, right?

```
 public StatementSourceSinkDefinition(Stmt stmt, Local local, Set<AccessPathTuple> accessPaths) {
	this.stmt = stmt;
	this.local = local;
	this.accessPaths = accessPaths;
}
```

If so, may I ask what should I pass to the `Set<AccessPathTuple> accessPaths` argument when use the constructor? null or?

**Comment by StevenArzt** [comment]
Your approach is correct. If you only want a local, e.g., ``$r0`` and not sequence of field dereferences ``$r0.fld1.fld2``, then you can simply pass ``null`` for the access path tuples.
