### ISSUE TITLE
Apologies for borrowing this thread as I am also experiencing this issue. Based on the description of the tool i have followed and used the 2.9 version dependencies jar file as i am intending to just execute its command line interface. However it is still not working on my end. May I know specifically which release should i be using in order to run the tool's command line interface?

### ISSUE THREAD

**Issue by SBz19** [secure-software-engineering/FlowDroid#390]
Apologies for borrowing this thread as I am also experiencing this issue. Based on the description of the tool i have followed and used the 2.9 version dependencies jar file as i am intending to just execute its command line interface. However it is still not working on my end. May I know specifically which release should i be using in order to run the tool's command line interface?

_Originally posted by @SBz19 in https://github.com/secure-software-engineering/FlowDroid/issues/369#issuecomment-926575235_

**Comment by flankerhqd** [comment]
Please use build from dev branch.
