### ISSUE TITLE
Always “Running incremental callback analysis for 0 components...”, repeat and never stop.

### ISSUE THREAD

**Issue by 99zikke** [secure-software-engineering/FlowDroid#418]
Hi, I'm using Fllowdroid to construct the call graph of an APK. And it always repeats the following output:

> [main] INFO soot.jimple.infoflow.android.SetupApplication - Initializing Soot...
> [main] INFO soot.jimple.infoflow.android.SetupApplication - Loading dex files...
> [main] INFO soot.jimple.infoflow.android.SetupApplication - ARSC file parsing took 0.0740727 seconds
> [main] INFO soot.jimple.infoflow.memory.MemoryWarningSystem - Registered a memory warning system for 4,908.15 MiB
> [main] INFO soot.jimple.infoflow.android.entryPointCreators.AndroidEntryPointCreator - Creating Android entry point for 139 components...
> [main] INFO soot.jimple.infoflow.android.SetupApplication - Constructing the callgraph...
> [main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Collecting callbacks in DEFAULT mode...
> [main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Callback analysis done.
> [main] INFO soot.jimple.infoflow.android.entryPointCreators.AndroidEntryPointCreator - Creating Android entry point for 146 components...
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.BroadcastReceiverEntryPointCreator - Cannot create valid constructor for com.sogou.commonlib.net.NetworkConnectChangedReceiver$NetworkListener, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.BroadcastReceiverEntryPointCreator - Cannot create valid constructor for com.meizu.cloud.pushsdk.b.e.c, because it is abstract and cannot substitute with subclass
> [main] INFO soot.jimple.infoflow.android.SetupApplication - Constructing the callgraph...
> [main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Running incremental callback analysis for 115 components...
> [main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Incremental callback analysis done.
> [main] INFO soot.jimple.infoflow.android.entryPointCreators.AndroidEntryPointCreator - Creating Android entry point for 146 components...
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.AndroidEntryPointCreator - Cannot create valid constructor for com.ss.android.crash.log.f$a, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.sogou.passportsdk.view.BaseDialog, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.BroadcastReceiverEntryPointCreator - Cannot create valid constructor for com.sogou.commonlib.net.NetworkConnectChangedReceiver$NetworkListener, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.widget.b$a, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for razerdp.basepopup.BasePopupWindow, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.BroadcastReceiverEntryPointCreator - Cannot create valid constructor for com.meizu.cloud.pushsdk.b.e.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.sogou.passportsdk.view.BaseDialog, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for sdk.meizu.auth.b.b, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.sogou.passportsdk.view.BaseDialog, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for sdk.meizu.auth.b.b, because it is an interface and cannot substitute with subclass
> [main] INFO soot.jimple.infoflow.android.SetupApplication - Constructing the callgraph...
> [main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Running incremental callback analysis for 39 components...
> [main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Incremental callback analysis done.
> [main] INFO soot.jimple.infoflow.android.entryPointCreators.AndroidEntryPointCreator - Creating Android entry point for 146 components...
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.sogou.passportsdk.view.BaseDialog, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.BroadcastReceiverEntryPointCreator - Cannot create valid constructor for com.sogou.commonlib.net.NetworkConnectChangedReceiver$NetworkListener, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.widget.b$a, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for razerdp.basepopup.BasePopupWindow, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.BroadcastReceiverEntryPointCreator - Cannot create valid constructor for com.meizu.cloud.pushsdk.b.e.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.sogou.passportsdk.view.BaseDialog, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for sdk.meizu.auth.b.b, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.sogou.passportsdk.view.BaseDialog, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for sdk.meizu.auth.b.b, because it is an interface and cannot substitute with subclass
> [main] INFO soot.jimple.infoflow.android.SetupApplication - Constructing the callgraph...
> [main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Running incremental callback analysis for 1 components...
> [main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Incremental callback analysis done.
> [main] INFO soot.jimple.infoflow.android.entryPointCreators.AndroidEntryPointCreator - Creating Android entry point for 146 components...
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.sogou.passportsdk.view.BaseDialog, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.BroadcastReceiverEntryPointCreator - Cannot create valid constructor for com.sogou.commonlib.net.NetworkConnectChangedReceiver$NetworkListener, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.widget.b$a, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for razerdp.basepopup.BasePopupWindow, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.BroadcastReceiverEntryPointCreator - Cannot create valid constructor for com.meizu.cloud.pushsdk.b.e.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.sogou.passportsdk.view.BaseDialog, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for sdk.meizu.auth.b.b, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.sogou.passportsdk.view.BaseDialog, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for sdk.meizu.auth.b.b, because it is an interface and cannot substitute with subclass
> [main] INFO soot.jimple.infoflow.android.SetupApplication - Constructing the callgraph...
> [main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Running incremental callback analysis for 0 components...
> [main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Incremental callback analysis done.
> [main] INFO soot.jimple.infoflow.android.entryPointCreators.AndroidEntryPointCreator - Creating Android entry point for 146 components...
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.sogou.passportsdk.view.BaseDialog, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.BroadcastReceiverEntryPointCreator - Cannot create valid constructor for com.sogou.commonlib.net.NetworkConnectChangedReceiver$NetworkListener, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.widget.b$a, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for razerdp.basepopup.BasePopupWindow, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.BroadcastReceiverEntryPointCreator - Cannot create valid constructor for com.meizu.cloud.pushsdk.b.e.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.sogou.passportsdk.view.BaseDialog, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for sdk.meizu.auth.b.b, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.sogou.passportsdk.view.BaseDialog, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for sdk.meizu.auth.b.b, because it is an interface and cannot substitute with subclass
> [main] INFO soot.jimple.infoflow.android.SetupApplication - Constructing the callgraph...
> [main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Running incremental callback analysis for 0 components...
> [main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Incremental callback analysis done.
> [main] INFO soot.jimple.infoflow.android.entryPointCreators.AndroidEntryPointCreator - Creating Android entry point for 146 components...
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.sogou.passportsdk.view.BaseDialog, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.BroadcastReceiverEntryPointCreator - Cannot create valid constructor for com.sogou.commonlib.net.NetworkConnectChangedReceiver$NetworkListener, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.widget.b$a, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for razerdp.basepopup.BasePopupWindow, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.BroadcastReceiverEntryPointCreator - Cannot create valid constructor for com.meizu.cloud.pushsdk.b.e.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.sogou.passportsdk.view.BaseDialog, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for sdk.meizu.auth.b.b, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.sogou.passportsdk.view.BaseDialog, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for sdk.meizu.auth.b.b, because it is an interface and cannot substitute with subclass
> [main] INFO soot.jimple.infoflow.android.SetupApplication - Constructing the callgraph...
> [main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Running incremental callback analysis for 0 components...
> [main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Incremental callback analysis done.
> [main] INFO soot.jimple.infoflow.android.entryPointCreators.AndroidEntryPointCreator - Creating Android entry point for 146 components...
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.sogou.passportsdk.view.BaseDialog, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.BroadcastReceiverEntryPointCreator - Cannot create valid constructor for com.sogou.commonlib.net.NetworkConnectChangedReceiver$NetworkListener, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.video.nativevideo.c, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.a.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.bytedance.sdk.openadsdk.core.widget.b$a, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for razerdp.basepopup.BasePopupWindow, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.BroadcastReceiverEntryPointCreator - Cannot create valid constructor for com.meizu.cloud.pushsdk.b.e.c, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.sogou.passportsdk.view.BaseDialog, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for sdk.meizu.auth.b.b, because it is an interface and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for com.sogou.passportsdk.view.BaseDialog, because it is abstract and cannot substitute with subclass
> [main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for sdk.meizu.auth.b.b, because it is an interface and cannot substitute with subclass
> [main] INFO soot.jimple.infoflow.android.SetupApplication - Constructing the callgraph...

As you can see, after the “Running incremental callback analysis for 0 components...” appears for the first time, all subsequent outputs are the same and will not stop. I had to manually terminate the program.
I'll be very grateful if you can help me.

**Comment by 99zikke** [comment]
And here are my code:
```
InfoflowAndroidConfiguration config = new InfoflowAndroidConfiguration();
config.getAnalysisFileConfig().setAndroidPlatformDir(jarsPath);
config.getAnalysisFileConfig().setTargetAPKFile(apkPath);
 config.setMergeDexFiles(true);

SetupApplication analyzer = new SetupApplication(config);
analyzer.constructCallgraph();
CallGraph appCallGraph = Scene.v().getCallGraph();
```
I found that if I set the "config.setMergeDexFiles(true);" it will not stop, but if I set the "config.setMergeDexFiles(false);" it will stop with an incomplete call graph.

**Comment by CCWUCMCTS** [comment]
Hello, I have encountered the same problem. Among the more than 5000 apks in drebin, dozens of them have this problem. This is how I solved it: run multiple threads so that the thread pool retains only one program, and if this program runs overtime, terminate it.
In addition, I only analyzed one such file and found that it was confused, which may be the reason for this.
Now I am analyzing MalDroid-2020 and encountered a new problem. I want to try to solve it by myself, so I won't talk about it here.

**Comment by 99zikke** [comment]
@CCWUCMCTS 
Hi, thank you for your comments!
You mean that you run multiple threads and each thread handles only one apk?
But I think this cannot solve this problem completely. Because I don't know how many apks in my data set will encounter this problem. Hi @StevenArzt , could you please help us? This is the link of my apk : https://drive.google.com/file/d/1aHSd-6DsvpePSUD5oaWELEt9oAYmQjo6/view?usp=sharing

**Comment by CCWUCMCTS** [comment]
> @CCWUCMCTS Hi, thank you for your comments! You mean that you run multiple threads and each thread handles only one apk? But I think this cannot solve this problem completely. Because I don't know how many apks in my data set will encounter this problem. Hi @StevenArzt , could you please help us? This is the link of my apk : https://drive.google.com/file/d/1aHSd-6DsvpePSUD5oaWELEt9oAYmQjo6/view?usp=sharing

Well, avoiding does not solve the problem. I also want to know what caused this error.

**Comment by StevenArzt** [comment]
You can set timeouts in the ``InfoflowConfiguration`` class or via the respective command-line options. If FlowDroid encounters such a timeout, it carries on with the partial results it has computed so far. You probably don't have the full results, but you have at least something.

It's normal to have multiple iterations of the callgraph algorithm, which works incrementally. Whenever new callbacks are detected, these are used as seeds for the next round of the callgraph analysis. The counter is slightly misleading, since reachable methods from views are added after the counter is printed. I have fixed this issue, so FlowDroid should now print a correct incremental counter.

I have not yet had the time to run your APK, but I assume that you just have very many callbacks. A callback cutoff (``InfoflowAndroidConfiguration.CallbackConfiguration.callbackAnalysisTimeout``) should help here (or ``-ct`` in the command-line application).

**Comment by 99zikke** [comment]
> 

Thank you for your help! Though I don't know what caused this problem, it works and I get part of the call graph which is important to me.
