### ISSUE TITLE
how to analysis ICC with IccTA and Soot?

### ISSUE THREAD

**Issue by jyjsunny** [secure-software-engineering/FlowDroid#435]
Hello，

Currently I'm trying to analyze the apk's permission management check, I have implemented the synchronous permission management check through Soot. However, my implementation lacks asynchrony, so I want to use IccTA to analyze with Soot, but don't know where to start.

Looking forward to your answer to my question, much appreciated!

**Comment by StevenArzt** [comment]
Do not confuse inter-component communication (e.g., intents sent between two activities) with asynchonous control flow (e.g., threads, executors). ICCTA deals with inter-component communication and you need to supply an ICC model. Asynchronous flow is handled by FlowDroid by default.

**Comment by jyjsunny** [comment]
Thank you very much for your reply! 
Does the ICC model you mentioned need me to build it myself?

**Comment by StevenArzt** [comment]
Yes, you can, for example, use IC3 to build the model: https://ieeexplore.ieee.org/abstract/document/7194563

**Comment by jyjsunny** [comment]
Thank you very much for your reply!
I will try it by myself.
