### ISSUE TITLE
Flowdroid cannot analyze some Android apps

### ISSUE THREAD

**Issue by Connor-fire** [secure-software-engineering/FlowDroid#436]
Hello,

Flowdroid is a very useful tool. I've been learning how to use flowdroid to generate application‘s function call graph recently. However, I found that the information in the figure below will appear when analyzing some applications, and it will not stop.

I look forward to your answer to my question. Thank you very much!
![image](https://user-images.githubusercontent.com/55130798/154219031-86ee14ad-84b5-4ba3-9f3f-7a9d626ea4b9.png)

**Comment by Connor-fire** [comment]
When I use the official Android SDK with API versions 29， the results are shown in the figure below.
![image](https://user-images.githubusercontent.com/55130798/154224560-26d73465-a401-4589-bb8b-6472faadb7a6.png)
`[main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Running incremental callback analysis for 0 components...
[main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Incremental callback analysis done.
[main] INFO soot.jimple.infoflow.android.entryPointCreators.AndroidEntryPointCreator - Creating Android entry point for 20 components...
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onAttachFragment(android.app.Fragment)
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onAttach(android.app.Activity)
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onCreate(android.os.Bundle)
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: android.view.View onCreateView(android.view.LayoutInflater,android.view.ViewGroup,android.os.Bundle)
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onViewCreated(android.view.View,android.os.Bundle)
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onActivityCreated(android.os.Bundle)
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onStart()
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onResume()
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onPause()
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onSaveInstanceState(android.os.Bundle)
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onStop()
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onDestroyView()
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onDestroy()
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onDetach()
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onAttachFragment(android.app.Fragment)
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onAttach(android.app.Activity)
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onCreate(android.os.Bundle)
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: android.view.View onCreateView(android.view.LayoutInflater,android.view.ViewGroup,android.os.Bundle)
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onViewCreated(android.view.View,android.os.Bundle)
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onActivityCreated(android.os.Bundle)
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onStart()
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onResume()
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onPause()
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onSaveInstanceState(android.os.Bundle)
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onStop()
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onDestroyView()
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onDestroy()
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.FragmentEntryPointCreator - Could not find Android entry point method: void onDetach()
[main] WARN soot.jimple.infoflow.android.entryPointCreators.components.ActivityEntryPointCreator - Cannot create valid constructor for org.openbmap.utils.v, because it is an interface and cannot substitute with subclass`

**Comment by StevenArzt** [comment]
This message simply indicates that a certain method does not exist in a component class and was skipped. That's not a problem. I'll remove the message, because it's expected behavior and such warnings simply confuse people (aside from bloating the log).

**Comment by Connor-fire** [comment]
Thank you for your reply.

However, Flowdroid seems to repeat the above information all the time. Trapped in an infinite loop. Unable to complete the construction of the call graph.

I use Flowdroid by importing jar packages into the project. Is there any solution.

**Comment by StevenArzt** [comment]
Can you provide the APK file on which this happens?

**Comment by Connor-fire** [comment]
Thank you very much for your help. The APK is in the compressed package.
[org.openbmap_27.zip](https://github.com/secure-software-engineering/FlowDroid/files/8087477/org.openbmap_27.zip)

**Comment by StevenArzt** [comment]
Its is a bug, but a strange one. Apparently, the same edges are re-created in new iterations of the callgraph construction, but multiple times. The number of edges keeps growing indefinitely, but if you make a set of the ``toString()`` outputs, this set reaches a fixpoint pretty soon. Since we fully delete the callgraph before running the next iteration, the only logical consequence is that some edges get created multiple times. I need to look into this more. It's strange that we don't see this with other apps.

Temporary workaround: Comment out the following line in ``SetupApplication.calculateCallbackMethods()``:
```
if (numPrevEdges < Scene.v().getCallGraph().size())
  hasChanged = true;
```

The other checks should normally be enough to ensure that FlowDroid doesn't terminate the callback analysis prematurely.

**Comment by Connor-fire** [comment]
Referring to your method, I commented out the two lines under the project `soot-infoflow-android`.But it didn't work.

**Comment by StevenArzt** [comment]
Does it work with the fix? The fix should make it unnecessary to comment out the two lines. The root cause that I identified was that FlowDroid kept instrumenting the same unit for ICCTA, i.e., it added the same lines over and over again. Therefore, the callgraph kept growing without limit.

**Comment by Connor-fire** [comment]
If I want to terminate the infinite loop of flowdroid. Do I need to comment out the above two lines?

**Comment by StevenArzt** [comment]
Just use the fixed version (develop branch) without any changes, that should be enough.

**Comment by Connor-fire** [comment]
OK, I see. You updated soot-info-android five hours ago.

**Comment by Connor-fire** [comment]
Thank you very much for your help.Are you considering releasing the latest jar package? I think it's necessary.

**Comment by StevenArzt** [comment]
We can do a new release on Maven Central at soem point, yes. In the meantime, please compile the "develop" branch using ``mvn install``.
