### ISSUE TITLE
How to build FlowDroid souce code on eclipse?

### ISSUE THREAD

**Issue by Connor-fire** [secure-software-engineering/FlowDroid#441]
I tried to import the flowdroid source code into eclipse and build it. But it prompts for an error in the build.

`[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building soot-infoflow-android 2.11.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for de.fraunhofer.sit.sse.flowdroid:soot-infoflow:jar:2.11.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.247 s
[INFO] Finished at: 2022-02-23T10:39:11+08:00
[INFO] Final Memory: 11M/213M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project soot-infoflow-android: Could not resolve dependencies for project de.fraunhofer.sit.sse.flowdroid:soot-infoflow-android:jar:2.11.0-SNAPSHOT: Could not find artifact de.fraunhofer.sit.sse.flowdroid:soot-infoflow:jar:2.11.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by StevenArzt** [comment]
Did you build FlowDroid using the pom file in the root folder? In that case, soot-infoflow is built before soot-infoflow-android is built and the snapshot should be there. You cannot build soot-infoflow-android as a standalone project.
