### ISSUE TITLE
How to set the para "accessPaths" of StatementSourceSinkDefinition to avoid NullPointerException error?

### ISSUE THREAD

**Issue by zhouyuhao1018** [secure-software-engineering/FlowDroid#442]
Hi,
I implement my own `ISourceSinkDefinitionProvider`, and using `StatementSourceSinkDefinition` to construct the Source I want.

In the [issue#387](https://github.com/secure-software-engineering/FlowDroid/issues/387) which is closed, you say that we can simply pass `null`  for the access path tuples. And I did so by  `new StatementSourceSinkDefinition(stmt,(Local) stringPara,null);`

However, when I runInfoflow(), `NullPointerException` error will happens at `soot.jimple.infoflow.android.source.AccessPathBasedSourceSinkManager.createSourceInfo()` . 

In this method, my debug results point out this error happens duo to the following codes:
```
                else if (def instanceof StatementSourceSinkDefinition) {
                    StatementSourceSinkDefinition ssdef = (StatementSourceSinkDefinition)def;
                    Iterator var17 = ssdef.getAccessPaths().iterator();

                    while(var17.hasNext()) {
                        AccessPathTuple apt = (AccessPathTuple)var17.next();
                        if (apt.getSourceSinkType().isSource()) {
                            aps.add(apt.toAccessPath(ssdef.getLocal(), manager, true));
                            apTuples.add(apt);
                        }
                    }
                }
```

due to I give `null` to the `accessPaths`, the error happens at `Iterator var17 = ssdef.getAccessPaths().iterator();`
Did I miss some important settings to avoid this? I wish your guidance!

**Comment by zhouyuhao1018** [comment]
In addition:
In `StatementSourceSinkDefinition` , there is `public StatementSourceSinkDefinition getSourceOnlyDefinition()` . Should I call this method, and use its return, not the constructor result, as one element of `Set<AbstractSourceSinkDefinition> SourceList` in my implemention of `ISourceSinkDefinitionProvider` ? I means that : 
```
AbstractSourceSinkDefinition source = new StatementSourceSinkDefinition(stmt, (Local) stringPara, null);
SourceList.add( source.getSourceOnlyDefinition() );
```
right ?

**Comment by StevenArzt** [comment]
Instead of null, you can pass ``AccessPathTuple.getBlankSourceTuple()``. That should avoid the ``null``. Apparently, I did not look properly at the case of ``StatementSourcesinkDefinition`` in the other issue.

**Comment by zhouyuhao1018** [comment]
Thanks for your reply!
With your guidance, I tried this by the following codes and FlowDroid successfully run.
```
Set<AccessPathTuple> accessPaths = new HashSet<>();
accessPaths.add( AccessPathTuple.getBlankSourceTuple() );
StatementSourceSinkDefinition source = new StatementSourceSinkDefinition(stmt, (Local) stringPara, accessPaths);
``` 
Although it runs successfully, FlowDroid reports 0 leaks, which confuses me a lot.
FlowDroid looks for sources and sinks successfully as the information shows in console, and the data flow in my test app is simple I think.

part of Console: 
```
[main] INFO soot.jimple.infoflow.android.source.AccessPathBasedSourceSinkManager - Created a SourceSinkManager with 1 sources, 1 sinks, and 89 callback methods.
[main] INFO soot.jimple.infoflow.android.SetupApplication - Collecting callbacks and building a callgraph took 0 seconds
[main] INFO soot.jimple.infoflow.android.SetupApplication - Running data flow analysis on D:\AppsForFDLDroidTest\APK\app-debug.apk with 3 sources and 1 sinks...
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Implicit flow tracking is NOT enabled
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Exceptional flow tracking is NOT enabled
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Running with a maximum access path length of 5
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Using path-agnostic result collection
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Recursive access path shortening is enabled
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Taint analysis enabled: true
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Using alias algorithm FlowSensitive
[main] INFO soot.jimple.infoflow.memory.MemoryWarningSystem - Registered a memory warning system for 9,789.75 MiB
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Callgraph construction took 0 seconds
[main] INFO soot.jimple.infoflow.codeOptimization.InterproceduralConstantValuePropagator - Removing side-effect free methods is enabled
[main] INFO soot.jimple.infoflow.codeOptimization.InterproceduralConstantValuePropagator - Removed %d call edges
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Dead code elimination took 0.4871629 seconds
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Callgraph has 9908 edges
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Starting Taint Analysis
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Using context- and flow-sensitive solver
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Using context- and flow-sensitive solver
[main] WARN soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Running with limited join point abstractions can break context-sensitive path builders
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Looking for sources and sinks...
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Source lookup done, found 3 sources and 1 sinks.
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Taint wrapper hits: 6
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Taint wrapper misses: 2
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - IFDS problem with 13 forward and 3 backward edges solved in 0 seconds, processing 0 results...
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Current memory consumption: 1168 MB
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Memory consumption after cleanup: 216 MB
[main] INFO soot.jimple.infoflow.memory.MemoryWarningSystem - Shutting down the memory warning system...
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Memory consumption after path building: 252 MB
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Path reconstruction took 0 seconds
[main] WARN soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - No results found.
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Data flow solver took 3960 seconds. Maximum memory consumption: 1168 MB
[main] INFO soot.jimple.infoflow.android.SetupApplication - Found 0 leaks
``` 

part of my test APP:

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
    
        ......
        textView = findViewById(R.id.textView);
        button1 = findViewById(R.id.button1);
        ......
        textView.setText(String.valueOf(myViewModel.getNumber()));

        button1.setOnClickListener(new View.OnClickListener() { 
            @Override
            public void onClick(View v) {
                myViewModel.setNumber(myViewModel.getNumber()+1);
                textView.setText(String.valueOf(myViewModel.getNumber()));
                save(myViewModel.getNumber());
            }
        });
    }
    
    ......
    
    private void save(int num){
        SharedPreferences sharedPreferences = getSharedPreferences("MainActivity", Context.MODE_PRIVATE);
        SharedPreferences.Editor editor = sharedPreferences.edit();
        editor.putInt("KeyMAIN",num);
        editor.apply();
    }

``` 

The statement `textView.setText(String.valueOf(myViewModel.getNumber()))` is a `StatementSourceSinkDefinition` source, whose `Local` para is the String used by setText(); And `editor.putInt("KeyMAIN",num)` is a `MethodSourceSinkDefinition `sink.

my test app is uploaded in zip.
[app-debug.zip](https://github.com/secure-software-engineering/FlowDroid/files/8138216/app-debug.zip)

**Comment by StevenArzt** [comment]
Your source definition is confusing to me. The Java statement

```
textView.setText(String.valueOf(myViewModel.getNumber()))
```

is split into multiple Jimple statements. That should be something like this:

```
a = myViewModel.getNumber();
b = String.valueOf(a);
textView.setText(b);
```

Jimple does not allow nested statements, so all statements are split up. If you set the last statement ``textView.setText(b);`` as a source, that doesn't influence other parts of the code, because the call to ``save`` does not depend on the local``b``. It calls the getter again, stores the result in a different local, and passes that other local to the ``save`` method.

Instead, you need to set the statement that calls ``getNumber()`` as the source. It might even be better to use a ``MethodSourceSinkDefinition`` on ``getNumber()``.

When looking at sources and sinks, it really makes sense to reason about the Jimple code, not the Java code.

**Comment by zhouyuhao1018** [comment]
sorry, I didn't express what I mean. Actually I mean Jimple.  Jimple codes of the java statement

```
textView.setText(String.valueOf(myViewModel.getNumber()));
save(myViewModel.getNumber());
```

are as follows:
```
$r3 = $r2.<com.example.viewmedeltest.MainActivity: com.example.viewmedeltest.MyViewModel myViewModel>;
$i0 = virtualinvoke $r3.<com.example.viewmedeltest.MyViewModel: int getNumber()>();
$r6 = staticinvoke <java.lang.String: java.lang.String valueOf(int)>($i0);
virtualinvoke $r5.<android.widget.TextView: void setText(java.lang.CharSequence)>($r6);
$r2 = r0.<com.example.viewmedeltest.MainActivity$1: com.example.viewmedeltest.MainActivity this$0>;
$r3 = $r2.<com.example.viewmedeltest.MainActivity: com.example.viewmedeltest.MyViewModel myViewModel>;
$i0 = virtualinvoke $r3.<com.example.viewmedeltest.MyViewModel: int getNumber()>();
staticinvoke <com.example.viewmedeltest.MainActivity: void access$000(com.example.viewmedeltest.MainActivity,int)>($r2, $i0);
``` 
Finally, `access$000` method will call `save` method.

The jimple statement `virtualinvoke $r5.<android.widget.TextView: void setText(java.lang.CharSequence)>($r6)`  is set as a source,  the local  `$r6` has taint `$i0` (due to  `java.lang.String valueOf(int)` in line 3 ) . The `$i0` will be pass to `access$000` method, and then  `save` method. 
However, you mean that, the second one  `$i0`  which is in line 7 and finally pass to  `access$000` method,  and  the first one in line 2; even they are the same local in  `onClick()` method, but they are seen as two by FlowDroid because of the getter again, right ?
So, if I want to get the data flow from the local  `$r6` or its taint `$i0` to the sink API 
`android.content.SharedPreferences$Editor putInt(java.lang.String,int)`  , actually I need set the statement
 `$i0 = virtualinvoke $r3.<com.example.viewmedeltest.MyViewModel: int getNumber()>()`  in line 7 as the source, right?

**Comment by zhouyuhao1018** [comment]
Thanks a lot !  Now, I have a clearer understanding of your words "as a source, that doesn't influence other parts of the code, because the call to `save` does not depend on the local`b`" !
I modified the source code of the app-debug.apk for my test, and FlowDroid successfully reports 1 leak !  as follows:
 
```
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - The sink interfaceinvoke $r3.<android.content.SharedPreferences$Editor: android.content.SharedPreferences$Editor putString(java.lang.String,java.lang.String)>("KeyMAIN", $r1) on line 145 in method <com.example.viewmedeltest.MainActivity: void saveTest(java.lang.String)> was called with values from the following sources:
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - - virtualinvoke $r5.<android.widget.TextView: void setText(java.lang.CharSequence)>($r4) on line 56 in method <com.example.viewmedeltest.MainActivity$1: void onClick(android.view.View)>
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Data flow solver took 54 seconds. Maximum memory consumption: 1527 MB
[main] INFO soot.jimple.infoflow.android.SetupApplication - Found 1 leaks
```

 PS:  Can FlowDroid reports the whole path of data flow? the result above only shows that which sink is called with which sources, can it reports the whole path to show how the source flow to sink step by step?

**Comment by lolicon** [comment]
> Thanks a lot ! Now, I have a clearer understanding of your words "as a source, that doesn't influence other parts of the code, because the call to `save` does not depend on the local`b`" ! I modified the source code of the app-debug.apk for my test, and FlowDroid successfully reports 1 leak ! as follows:
> 
> ```
> [main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - The sink interfaceinvoke $r3.<android.content.SharedPreferences$Editor: android.content.SharedPreferences$Editor putString(java.lang.String,java.lang.String)>("KeyMAIN", $r1) on line 145 in method <com.example.viewmedeltest.MainActivity: void saveTest(java.lang.String)> was called with values from the following sources:
> [main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - - virtualinvoke $r5.<android.widget.TextView: void setText(java.lang.CharSequence)>($r4) on line 56 in method <com.example.viewmedeltest.MainActivity$1: void onClick(android.view.View)>
> [main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Data flow solver took 54 seconds. Maximum memory consumption: 1527 MB
> [main] INFO soot.jimple.infoflow.android.SetupApplication - Found 1 leaks
> ```
> 
> PS: Can FlowDroid reports the whole path of data flow? the result above only shows that which sink is called with which sources, can it reports the whole path to show how the source flow to sink step by step?

command line `-pr fast` or code `config.getPathConfiguration().setPathReconstructionMode(PathReconstructionMode.Fast);`

**Comment by zhouyuhao1018** [comment]
> 

thanks! I have already solved it.
