### ISSUE TITLE
Question about using soot-inflow-summary to generate summary of android sdk

### ISSUE THREAD

**Issue by LeoYelton** [secure-software-engineering/FlowDroid#448]
I try to not directly using command line tool to generate **android.jar** summary because it need android.menifest,apk etc. Instead,I copy the main logic of **"soot.jimple.infoflow.methodSummary.Main"** try to analyse some compiled classes. It always get result as `**"<?xml version="1.0" ?><summary fileFormatVersion="103"><methods></methods></summary>”** `. Do we have an example using it?  It differs from the result of ./summarial folder when I use summary generator of same class,such as widget.CheckBox. 
I use same version as yours benchmark version. Android 6.0  which runs same result as 5.0 either.

**Comment by StevenArzt** [comment]
The command-line application is able to analyze the Android platform JAR files. It does not require any manifest, because it handles JARs and not apps. However, note that you need a real Android JAR file, not the one from the SDK. The JARs in the SDK are stub files, i.e., every method only throws an exception. This file is only used for linking apps, the real implementation is on the device.

In case you have further issues, please provide your full command line.

**Comment by LeoYelton** [comment]
Thank for you promptly reply,professor. I've tried several commands and just reviewed your paper minutes before. I may have a mistake of trying it . Summary-generator command tool is an independent project from the soot-inflow-cmd tool. And I tried them on soot-inflow-cmd. Thanks a million.
I'm not so familliar with android develop. Where can I download **the real Android JAR file**? Do you mean the images of android or I need to compile android source code on my own? I don't find any class or jar file in android iso files.

**Comment by Yelixing** [comment]
Thanks, I've found it under android folder.

**Comment by StevenArzt** [comment]
You can find some older versions of the platform JARs here: https://github.com/Sable/android-platforms. For the newer platform versions, you need to compile the AOSP (Android Open Source Project) on your own.

**Comment by LeoYelton** [comment]
Thank you all the same ,professor. I wish to meet a teacher like you in the future. I download from the upside website.  It is same from the android studio SDK official.  I'm trying to ignore cases about android right now. Maybe it'll be a hard work to write it mannually.
