### ISSUE TITLE
Build error for soot-infoflow-summaries

### ISSUE THREAD

**Issue by dah-fari7009** [secure-software-engineering/FlowDroid#463]
Hi,

When attempting to build the latest version of the project (on develop branch) using Maven in IntelliJ, I get a compilation error for soot-infoflow-summaries :  
**incompatible types: java.util.Set<soot.jimple.infoflow.solver.EndSummary<soot.Unit,soot.jimple.infoflow.data.Abstraction>> cannot be converted to java.util.Set<heros.solver.Pair<soot.Unit,soot.jimple.infoflow.data.Abstraction>>**
![image](https://user-images.githubusercontent.com/35702512/168158895-614e5c36-afdf-49c1-b793-70a6251716a7.png)

The error is occuring in **taintWrappers.SummaryTaintWrapper**
![image](https://user-images.githubusercontent.com/35702512/168153766-4f4c9784-14f0-4146-beea-79eb41cfe614.png)

I get this error with both "mvn install" and Build Project in IntelliJ.

**Comment by StevenArzt** [comment]
This was indeed a bug from an incomplete refactoring. I have fixed it.

**Comment by dah-fari7009** [comment]
Thank you!
