### ISSUE TITLE
FlowDroid fails to propagate taint when involving type casting

### ISSUE THREAD

**Issue by jimmy66688** [secure-software-engineering/FlowDroid#470]
considering this running example:
```java
public class Case21CastingAfterMapGet {

    public static void main(String[] args) {
        Map<String, Object> conf = new HashMap<String, Object>();
        conf.put("mode", 'c');
        conf.put("jobs", 1);
        char mode = (char) (conf.get("mode"));

        if (mode == 'c') {
            System.out.println("mode is c");
        }

        int jobs = (int) (conf.get("jobs"));
        if (jobs == 1){
            System.out.println("jobs is 1");
        }
    }
}
```
the source method signature is `"<java.util.Map: java.lang.Object get(java.lang.Object)>"`
the sink we foucus on is every `if statement`, so I instrument a dummy sink `void sink(Object o)` before every if statment, so that i can track `if`
the log shows that `[main] WARN  No results found.`
so, the question i wanna know is `What causes this?`, i found a paper `Analyzing Android Taint Analysis Tools: FlowDroid, Amandroid, and DroidSafe` described this problem, but without any solution.

**Comment by jimmy66688** [comment]
InfoflowConfiguration is:
```java
    protected static InfoflowConfiguration globalConf;
    public static void initEnv() {
        // reset soot env
        soot.G.reset();
        System.gc();
        // init configuration

        // config information flow
        globalConf = new InfoflowConfiguration();
        //more precise call graph algorithm
        globalConf.setCallgraphAlgorithm(InfoflowConfiguration.CallgraphAlgorithm.SPARK);
        globalConf.setImplicitFlowMode(InfoflowConfiguration.ImplicitFlowMode.AllImplicitFlows);

        // globalConf.setCodeEliminationMode(InfoflowConfiguration.CodeEliminationMode.PropagateConstants);
       globalConf.setCodeEliminationMode(InfoflowConfiguration.CodeEliminationMode.NoCodeElimination);
        globalConf.getAccessPathConfiguration().setAccessPathLength(20);
        globalConf.getSolverConfiguration().setDataFlowSolver(InfoflowConfiguration.DataFlowSolver.ContextFlowSensitive);
        globalConf.setMaxThreadNum(-1);

        globalConf.setInspectSources(false);
        globalConf.setInspectSinks(false);

        globalConf.setAliasingAlgorithm(InfoflowConfiguration.AliasingAlgorithm.FlowSensitive);

        globalConf.setFlowSensitiveAliasing(true);
        globalConf.setStopAfterFirstFlow(false);
        globalConf.setStaticFieldTrackingMode(InfoflowConfiguration.StaticFieldTrackingMode.ContextFlowSensitive);
        // do not track exception
        globalConf.setEnableExceptionTracking(false);
        globalConf.setOneSourceAtATime(true);
        globalConf.getPathConfiguration().setPathReconstructionMode(InfoflowConfiguration.PathReconstructionMode.Precise);

        globalConf.getSolverConfiguration().setMaxJoinPointAbstractions(-1);
        LOGGER.info("information flow config done.");
    }
```

**Comment by StevenArzt** [comment]
How did you specify your sources and sinks? Did you just place the map-get into ``SourcesAndSinks.txt``? That won't work. This simple definition format assumes that the tainted value is the return value of the method for which you provide the signature. In your case, you want to taint the base object. You can use the much more expressive XML format for sources and sinks. Have a look at the files in ``soot-infoflow-android/testXmlParser`` for an example. In ``complete.xml``, there is a taint on the base object that you can study.

The paper would have benefited from asking here...

Concerning your configuration: Why do you enable "one source at a time"? There are only very few use cases for this option. Access Path length 20 is quite a lot and is very unlikely to scale on real-world applications.

**Comment by jimmy66688** [comment]
Thank for your concerning, I am a freshman. I use a class `MapGetSourceSinkManager` implements `ISourceSinkManager` to specify my sources and sinks. 
Most of the code copy from `DefaultSourceSinkManager`, only diff in method `boolean isSourceMethod(InfoflowManager manager, Stmt sCallSite)`.
I modified the `globalConf.setCallgraphAlgorithm(InfoflowConfiguration.CallgraphAlgorithm.SPARK);` to `globalConf.setCallgraphAlgorithm(InfoflowConfiguration.CallgraphAlgorithm.RTA);`, the results successfully found.
```
  - The sink staticinvoke <analysis.option.MySink: void sink(java.lang.Object)>(mode) on line 14 in method <objectiveProgram.Case21CastingAfterMapGet: void main(java.lang.String[])> was called with values from the following sources:
  - - $stack0#15 = interfaceinvoke conf.<java.util.Map: java.lang.Object get(java.lang.Object)>("mode") on line 12 in method <objectiveProgram.Case21CastingAfterMapGet: void main(java.lang.String[])>
  - 	on Path: 
  - 	 -> <objectiveProgram.Case21CastingAfterMapGet: void main(java.lang.String[])>
  - 		 -> $stack0#15 = interfaceinvoke conf.<java.util.Map: java.lang.Object get(java.lang.Object)>("mode")
  - 	 -> <objectiveProgram.Case21CastingAfterMapGet: void main(java.lang.String[])>
  - 		 -> $stack0#16 = (java.lang.Character) $stack0#15
  - 	 -> <objectiveProgram.Case21CastingAfterMapGet: void main(java.lang.String[])>
  - 		 -> mode = virtualinvoke $stack0#16.<java.lang.Character: char charValue()>()
  - 	 -> <java.lang.Character: char charValue()>
  - 		 -> $stack0#2 = l0.<java.lang.Character: char value>
  - 	 -> <java.lang.Character: char charValue()>
  - 		 -> return $stack0#2
  - 	 -> <objectiveProgram.Case21CastingAfterMapGet: void main(java.lang.String[])>
  - 		 -> staticinvoke <analysis.option.MySink: void sink(java.lang.Object)>(mode)
  - The sink staticinvoke <analysis.option.MySink: void sink(java.lang.Object)>(jobs) on line 19 in method <objectiveProgram.Case21CastingAfterMapGet: void main(java.lang.String[])> was called with values from the following sources:
  - - $stack0#24 = interfaceinvoke conf.<java.util.Map: java.lang.Object get(java.lang.Object)>("jobs") on line 18 in method <objectiveProgram.Case21CastingAfterMapGet: void main(java.lang.String[])>
  - 	on Path: 
  - 	 -> <objectiveProgram.Case21CastingAfterMapGet: void main(java.lang.String[])>
  - 		 -> $stack0#24 = interfaceinvoke conf.<java.util.Map: java.lang.Object get(java.lang.Object)>("jobs")
  - 	 -> <objectiveProgram.Case21CastingAfterMapGet: void main(java.lang.String[])>
  - 		 -> $stack0#25 = (java.lang.Integer) $stack0#24
  - 	 -> <objectiveProgram.Case21CastingAfterMapGet: void main(java.lang.String[])>
  - 		 -> jobs = virtualinvoke $stack0#25.<java.lang.Integer: int intValue()>()
  - 	 -> <java.lang.Integer: int intValue()>
  - 		 -> $stack0#2 = l0.<java.lang.Integer: int value>
  - 	 -> <java.lang.Integer: int intValue()>
  - 		 -> return $stack0#2
  - 	 -> <objectiveProgram.Case21CastingAfterMapGet: void main(java.lang.String[])>
  - 		 -> staticinvoke <analysis.option.MySink: void sink(java.lang.Object)>(jobs)
```

**So, the question is: Why SPARK can not propagate taint in this case**

**Comment by StevenArzt** [comment]
RTA performs an over-approximation. This may lead to additional leaks. However, it is not a proper solution in most cases.

Your second post seems to relate to another test application. There is no call to ``sink()`` in the original code you posted. Please stick to a consistent example to avoid confusion.

For proper handling of library classes such as ``HashMap``, you need to enable a taint wrapper. I'd recommend the ``SummaryTaintWrapper`` from StubDroid.

Your approach of duplicating the source/sink manager is technically possible, but unnecessarily complex. You can use FlowDroid's built-in mechanisms such as the XML-based specification language.

**Comment by jimmy66688** [comment]
Sorry, I describe my case not clearly. I instrument a sink `void sink(Object o)` before if statement so that i can track all if statement.
As for `TaintWrapper` and `XML sources/sinks manager`, I would give it a try.Until now, I only use `soot-infoflow` without `soot-infoflow-android` because I analyze the traditional Java program, not Android program.
Thanks for your reply.

**Comment by zhouyuhao1018** [comment]
> How did you specify your sources and sinks? Did you just place the map-get into `SourcesAndSinks.txt`? That won't work. This simple definition format assumes that the tainted value is the return value of the method for which you provide the signature. In your case, you want to taint the base object. You can use the much more expressive XML format for sources and sinks. Have a look at the files in `soot-infoflow-android/testXmlParser` for an example. In `complete.xml`, there is a taint on the base object that you can study.
> 
> The paper would have benefited from asking here...
> 
> Concerning your configuration: Why do you enable "one source at a time"? There are only very few use cases for this option. Access Path length 20 is quite a lot and is very unlikely to scale on real-world applications.

Sorry, I am a freshman who is learning FlowDroid, and I wanna know why you say " In your case, you want to taint the base object "? 
If he places the map-get method signature `<java.util.Map: java.lang.Object get(java.lang.Object)>` into SourcesAndSinks.txt,  Is this method's return value a taint that will taint the leftOp ? Why does he need to taint the base object ?

**Comment by StevenArzt** [comment]
``get`` is a sink, that's not a problem The leak is detected if at least one argument passed to the sink method is tainted. The problem lies with the source:

```
conf.put("mode", 'c');
```

You need to taint the base object ``conf``. In the simple ``SourcesAndSinks.txt`` file, FlowDroid expects that the return value is tainted, e.g.,

```
String secret = source();
```

You have a special case, and the more expressive XML format for sources and sinks can be used to model such cases.

**Comment by jimmy66688** [comment]
> RTA performs an over-approximation. This may lead to additional leaks. However, it is not a proper solution in most cases.
> 
> Your second post seems to relate to another test application. There is no call to `sink()` in the original code you posted. Please stick to a consistent example to avoid confusion.
> 
> For proper handling of library classes such as `HashMap`, you need to enable a taint wrapper. I'd recommend the `SummaryTaintWrapper` from StubDroid.
> 
> Your approach of duplicating the source/sink manager is technically possible, but unnecessarily complex. You can use FlowDroid's built-in mechanisms such as the XML-based specification language.

I am considering: Is the real problem in handling of library class? 
`conf.get("mode")` is source.
`if (mode == 'c')` is sink.
My analysis successfully identify source and sink.
Using `CallgraphAlgorithm.SPARK` can not build infoflow path, but `CallgraphAlgorithm.RTA` can! Is there some problem in point-to analysis? I use FlowDroid version 2.8.
Type casting between source and sink. Type casting involved `<java.lang.Character: char charValue()>()`, that means I need a taint wrapper to handling the `<java.lang.Character: char charValue()>()` method?

**Comment by zhouyuhao1018** [comment]
> > RTA performs an over-approximation. This may lead to additional leaks. However, it is not a proper solution in most cases.
> > Your second post seems to relate to another test application. There is no call to `sink()` in the original code you posted. Please stick to a consistent example to avoid confusion.
> > For proper handling of library classes such as `HashMap`, you need to enable a taint wrapper. I'd recommend the `SummaryTaintWrapper` from StubDroid.
> > Your approach of duplicating the source/sink manager is technically possible, but unnecessarily complex. You can use FlowDroid's built-in mechanisms such as the XML-based specification language.
> 
> I considering: Is the real problem in handling of library class? `conf.get("mode")` is source. `if (mode == 'c')` is sink. My analysis is successfully identify source and sink. Using `CallgraphAlgorithm.SPARK` can not build infoflow path, but `CallgraphAlgorithm.RTA` can! Is there some problem in point-to analysis? I use FlowDroid version 2.8. Type casting between source and sink. Type casting involved `<java.lang.Character: char charValue()>()`, that means I need a taint wrapper to handling the `<java.lang.Character: char charValue()>()` method?

May I ask how do you define the stmt `if (mode == 'c')` as a sink? do you use the `StatementSourceSinkDefinition` with its constructor and pass the if stmt and local mode to it?

**Comment by jimmy66688** [comment]
> 



> > > RTA performs an over-approximation. This may lead to additional leaks. However, it is not a proper solution in most cases.
> > > Your second post seems to relate to another test application. There is no call to `sink()` in the original code you posted. Please stick to a consistent example to avoid confusion.
> > > For proper handling of library classes such as `HashMap`, you need to enable a taint wrapper. I'd recommend the `SummaryTaintWrapper` from StubDroid.
> > > Your approach of duplicating the source/sink manager is technically possible, but unnecessarily complex. You can use FlowDroid's built-in mechanisms such as the XML-based specification language.
> > 
> > 
> > I considering: Is the real problem in handling of library class? `conf.get("mode")` is source. `if (mode == 'c')` is sink. My analysis is successfully identify source and sink. Using `CallgraphAlgorithm.SPARK` can not build infoflow path, but `CallgraphAlgorithm.RTA` can! Is there some problem in point-to analysis? I use FlowDroid version 2.8. Type casting between source and sink. Type casting involved `<java.lang.Character: char charValue()>()`, that means I need a taint wrapper to handling the `<java.lang.Character: char charValue()>()` method?
> 
> May I ask how do you define the stmt `if (mode == 'c')` as a sink? do you use the `StatementSourceSinkDefinition` with its constructor and pass the if stmt and local mode to it?

I instrument a customize sink method before if statement.You can think about `if (mode == 'c')` to `sink(mode); if (mode == 'c')` in jimple IR.

**Comment by jimmy66688** [comment]
I rewrite my running example:
```java
public class Case21MapGetChar {

    public static void main(String[] args) {
        Map<String, Object> conf = new HashMap<String, Object>();
        conf.put("mode", 'c');
        conf.put("jobs", 1);
        char mode = (char) (conf.get("mode"));
        System.out.println(mode);
        int jobs = (int) (conf.get("jobs"));
        System.out.println(jobs);
    }
}
```
The running example in jimple:
```
public class objectiveProgram.Case21MapGetChar extends java.lang.Object
{

    public void <init>()
    {
        objectiveProgram.Case21MapGetChar r0;

        r0 := @this: objectiveProgram.Case21MapGetChar;

        specialinvoke r0.<java.lang.Object: void <init>()>();

        return;
    }

    public static void main(java.lang.String[])
    {
        java.io.PrintStream $r5, $r8;
        java.util.HashMap $r0;
        char $c0;
        java.lang.String[] r9;
        java.lang.Integer $r2, $r7;
        java.lang.Character $r1, $r4;
        int $i1;
        java.lang.Object $r3, $r6;

        r9 := @parameter0: java.lang.String[];

        $r0 = new java.util.HashMap;

        specialinvoke $r0.<java.util.HashMap: void <init>()>();

        $r1 = staticinvoke <java.lang.Character: java.lang.Character valueOf(char)>(99);

        interfaceinvoke $r0.<java.util.Map: java.lang.Object put(java.lang.Object,java.lang.Object)>("mode", $r1);

        $r2 = staticinvoke <java.lang.Integer: java.lang.Integer valueOf(int)>(1);

        interfaceinvoke $r0.<java.util.Map: java.lang.Object put(java.lang.Object,java.lang.Object)>("jobs", $r2);

        $r3 = interfaceinvoke $r0.<java.util.Map: java.lang.Object get(java.lang.Object)>("mode");

        $r4 = (java.lang.Character) $r3;

        $c0 = virtualinvoke $r4.<java.lang.Character: char charValue()>();

        $r5 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $r5.<java.io.PrintStream: void println(char)>($c0);

        $r6 = interfaceinvoke $r0.<java.util.Map: java.lang.Object get(java.lang.Object)>("jobs");

        $r7 = (java.lang.Integer) $r6;

        $i1 = virtualinvoke $r7.<java.lang.Integer: int intValue()>();

        $r8 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $r8.<java.io.PrintStream: void println(int)>($i1);

        return;
    }
}

```
Source and Sink defined in `sourcesink.xml`:
```xml
<sinkSources>
	<category id="NO_CATEGORY">
		<method signature="&lt;java.util.Map: java.lang.Object get(java.lang.Object)&gt;">

			<return type="java.lang.Object">
				<accessPath isSource="true" isSink="false" /> 
			</return>

		</method>
		<method signature="&lt;java.io.PrintStream: void println(char)&gt;">
			<param index="0" type="char">
				<accessPath isSource="false" isSink="true">  
					<!-- Wenn leer, dann primitiver Datentyp (int, double, String,...)-->
				</accessPath>
			</param>
		</method>
	</category>
</sinkSources>

```
My InfoflowConfig is :
```java
        // config information flow
        globalConf = new InfoflowConfiguration();
        //more precise call graph algorithm
        globalConf.setCallgraphAlgorithm(InfoflowConfiguration.CallgraphAlgorithm.SPARK);
        globalConf.setImplicitFlowMode(InfoflowConfiguration.ImplicitFlowMode.AllImplicitFlows);


       globalConf.setCodeEliminationMode(InfoflowConfiguration.CodeEliminationMode.NoCodeElimination);
        globalConf.getAccessPathConfiguration().setAccessPathLength(10);
        globalConf.getSolverConfiguration().setDataFlowSolver(InfoflowConfiguration.DataFlowSolver.ContextFlowSensitive);
        globalConf.setMaxThreadNum(-1);

        globalConf.setInspectSources(false);
        globalConf.setInspectSinks(false);

        globalConf.setAliasingAlgorithm(InfoflowConfiguration.AliasingAlgorithm.FlowSensitive);

        globalConf.setFlowSensitiveAliasing(true);
        globalConf.setStopAfterFirstFlow(false);
        globalConf.setStaticFieldTrackingMode(InfoflowConfiguration.StaticFieldTrackingMode.ContextFlowSensitive);
        // do not track exception
        globalConf.setEnableExceptionTracking(false);


        globalConf.getPathConfiguration().setPathReconstructionMode(InfoflowConfiguration.PathReconstructionMode.Precise);

        globalConf.getSolverConfiguration().setMaxJoinPointAbstractions(-1);
```
I run the taint analysis with `computeInfoflow(appPath, libPath, entryPoint, new DefaultSourceSinkManager(XMLSourceSinkParser.fromFile("sourcesink.xml")));`
**Finally, the log print:**
```
 - Looking for sources and sinks...
 - Source found: $stack0#15 = interfaceinvoke $stack0#1.<java.util.Map: java.lang.Object get(java.lang.Object)>("mode") in <edu.sysu.jimmy.objectiveProgram.Case21MapGetChar: void main(java.lang.String[])>
 - Sink found: virtualinvoke $stack0#18.<java.io.PrintStream: void println(char)>($stack0#17) in <edu.sysu.jimmy.objectiveProgram.Case21MapGetChar: void main(java.lang.String[])>
 - Source found: $stack0#22 = interfaceinvoke $stack0#1.<java.util.Map: java.lang.Object get(java.lang.Object)>("jobs") in  - Source lookup done, found 3 sources and 1 sinks.
 - Path reconstruction took 0 seconds
 - No results found.
```
**So, what's going on?I am confusing at the "No results found."**@[StevenArzt](https://github.com/StevenArzt) Can you hep me ?Thanks!

**Comment by jimmy66688** [comment]
I rewrite my running example:
```java
public class Case21MapGetChar {

    public static void main(String[] args) {
        Map<String, Object> conf = new HashMap<String, Object>();
        conf.put("mode", 'c');
        conf.put("jobs", 1);
        char mode = (char) (conf.get("mode"));
        System.out.println(mode);
        int jobs = (int) (conf.get("jobs"));
        System.out.println(jobs);
    }
}
```
The running example in jimple:
```
public class objectiveProgram.Case21MapGetChar extends java.lang.Object
{

    public void <init>()
    {
        objectiveProgram.Case21MapGetChar r0;

        r0 := @this: objectiveProgram.Case21MapGetChar;

        specialinvoke r0.<java.lang.Object: void <init>()>();

        return;
    }

    public static void main(java.lang.String[])
    {
        java.io.PrintStream $r5, $r8;
        java.util.HashMap $r0;
        char $c0;
        java.lang.String[] r9;
        java.lang.Integer $r2, $r7;
        java.lang.Character $r1, $r4;
        int $i1;
        java.lang.Object $r3, $r6;

        r9 := @parameter0: java.lang.String[];

        $r0 = new java.util.HashMap;

        specialinvoke $r0.<java.util.HashMap: void <init>()>();

        $r1 = staticinvoke <java.lang.Character: java.lang.Character valueOf(char)>(99);

        interfaceinvoke $r0.<java.util.Map: java.lang.Object put(java.lang.Object,java.lang.Object)>("mode", $r1);

        $r2 = staticinvoke <java.lang.Integer: java.lang.Integer valueOf(int)>(1);

        interfaceinvoke $r0.<java.util.Map: java.lang.Object put(java.lang.Object,java.lang.Object)>("jobs", $r2);

        $r3 = interfaceinvoke $r0.<java.util.Map: java.lang.Object get(java.lang.Object)>("mode");

        $r4 = (java.lang.Character) $r3;

        $c0 = virtualinvoke $r4.<java.lang.Character: char charValue()>();

        $r5 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $r5.<java.io.PrintStream: void println(char)>($c0);

        $r6 = interfaceinvoke $r0.<java.util.Map: java.lang.Object get(java.lang.Object)>("jobs");

        $r7 = (java.lang.Integer) $r6;

        $i1 = virtualinvoke $r7.<java.lang.Integer: int intValue()>();

        $r8 = <java.lang.System: java.io.PrintStream out>;

        virtualinvoke $r8.<java.io.PrintStream: void println(int)>($i1);

        return;
    }
}

```
Source and Sink defined in `sourcesink.xml`:
```xml
<sinkSources>
	<category id="NO_CATEGORY">
		<method signature="&lt;java.util.Map: java.lang.Object get(java.lang.Object)&gt;">

			<return type="java.lang.Object">
				<accessPath isSource="true" isSink="false" /> 
			</return>

		</method>
		<method signature="&lt;java.io.PrintStream: void println(char)&gt;">
			<param index="0" type="char">
				<accessPath isSource="false" isSink="true">  
					<!-- Wenn leer, dann primitiver Datentyp (int, double, String,...)-->
				</accessPath>
			</param>
		</method>
	</category>
</sinkSources>

```
My InfoflowConfig is :
```java
        // config information flow
        globalConf = new InfoflowConfiguration();
        //more precise call graph algorithm
        globalConf.setCallgraphAlgorithm(InfoflowConfiguration.CallgraphAlgorithm.SPARK);
        globalConf.setImplicitFlowMode(InfoflowConfiguration.ImplicitFlowMode.AllImplicitFlows);


       globalConf.setCodeEliminationMode(InfoflowConfiguration.CodeEliminationMode.NoCodeElimination);
        globalConf.getAccessPathConfiguration().setAccessPathLength(10);
        globalConf.getSolverConfiguration().setDataFlowSolver(InfoflowConfiguration.DataFlowSolver.ContextFlowSensitive);
        globalConf.setMaxThreadNum(-1);

        globalConf.setInspectSources(false);
        globalConf.setInspectSinks(false);

        globalConf.setAliasingAlgorithm(InfoflowConfiguration.AliasingAlgorithm.FlowSensitive);

        globalConf.setFlowSensitiveAliasing(true);
        globalConf.setStopAfterFirstFlow(false);
        globalConf.setStaticFieldTrackingMode(InfoflowConfiguration.StaticFieldTrackingMode.ContextFlowSensitive);
        // do not track exception
        globalConf.setEnableExceptionTracking(false);


        globalConf.getPathConfiguration().setPathReconstructionMode(InfoflowConfiguration.PathReconstructionMode.Precise);

        globalConf.getSolverConfiguration().setMaxJoinPointAbstractions(-1);
```
I run the taint analysis with `computeInfoflow(appPath, libPath, entryPoint, new DefaultSourceSinkManager(XMLSourceSinkParser.fromFile("sourcesink.xml")));`
**Finally, the log print:**
```
 - Looking for sources and sinks...
 - Source found: $stack0#15 = interfaceinvoke $stack0#1.<java.util.Map: java.lang.Object get(java.lang.Object)>("mode") in <objectiveProgram.Case21MapGetChar: void main(java.lang.String[])>
 - Sink found: virtualinvoke $stack0#18.<java.io.PrintStream: void println(char)>($stack0#17) in <objectiveProgram.Case21MapGetChar: void main(java.lang.String[])>
 - Source found: $stack0#22 = interfaceinvoke $stack0#1.<java.util.Map: java.lang.Object get(java.lang.Object)>("jobs") in  - Source lookup done, found 3 sources and 1 sinks.
 - Path reconstruction took 0 seconds
 - No results found.
```
**So, what's going on?I am confusing at the "No results found."**@[StevenArzt](https://github.com/StevenArzt) Can you hep me ?Thanks!

**Comment by PhoenixMallu** [comment]
> > > > RTA performs an over-approximation. This may lead to additional leaks. However, it is not a proper solution in most cases.
> > > > Your second post seems to relate to another test application. There is no call to `sink()` in the original code you posted. Please stick to a consistent example to avoid confusion.
> > > > For proper handling of library classes such as `HashMap`, you need to enable a taint wrapper. I'd recommend the `SummaryTaintWrapper` from StubDroid.
> > > > Your approach of duplicating the source/sink manager is technically possible, but unnecessarily complex. You can use FlowDroid's built-in mechanisms such as the XML-based specification language.
> > > 
> > > 
> > > I considering: Is the real problem in handling of library class? `conf.get("mode")` is source. `if (mode == 'c')` is sink. My analysis is successfully identify source and sink. Using `CallgraphAlgorithm.SPARK` can not build infoflow path, but `CallgraphAlgorithm.RTA` can! Is there some problem in point-to analysis? I use FlowDroid version 2.8. Type casting between source and sink. Type casting involved `<java.lang.Character: char charValue()>()`, that means I need a taint wrapper to handling the `<java.lang.Character: char charValue()>()` method?
> > 
> > 
> > May I ask how do you define the stmt `if (mode == 'c')` as a sink? do you use the `StatementSourceSinkDefinition` with its constructor and pass the if stmt and local mode to it?
> 
> I instrument a customize sink method before if statement.You can think about `if (mode == 'c')` to `sink(mode); if (mode == 'c')` in jimple IR.

@jimmy66688 @zhouyuhao1018 how do u instrument a customised sink before if statements can you please explain a bit..thanks
