### ISSUE TITLE
No superclass when extending abstract class

### ISSUE THREAD

**Issue by dah-fari7009** [secure-software-engineering/FlowDroid#480]
Hi,

I'm running Flowdroid (develop branch version) to build a callgraph for an apk with Android 25.
I noticed a number of activities have no superclass(es), thus are not resolved as activities (i.e not extending android.app.Activity), which implies lifecycles and callbacks will be missing for those. It seems, this case occurs when the activity extends an abstract class.

```
public abstract class IHRActivity extends AppCompatActivity
public class SplashActivity extends IHRActivity
```

Here, both `SootClass.getSuperClass()` and` Scene.v().getActiveHierarchy().getSuperclassesOf()` will return nothing for SplashActivity

I was wondering if that was the intended behavior, and if not what could be causing the issue.

Thanks

**Comment by StevenArzt** [comment]
This seems like a Soot issue. If ``getSuperClass()`` already returns ``null``, the hierarchy cannot work. Have you tried disassembling the APK with Baksamli to see if the ``SplashActivity`` actually has the proper superclass in place?

**Comment by dah-fari7009** [comment]
Hi,

Yes I have (with jadx). I also get the same issue when running just Soot, would you mind referring me to where the class hierarchy is resolved so I can take a further look at what might be causing the issue?

**Comment by StevenArzt** [comment]
Have a look at ``DexClassLoader.makeSootClass`` in Soot, which calls ``SootClass.setSuperclass``. Maybe this call isn't made or ``null`` is passed.

**Comment by dah-fari7009** [comment]
Thank you!

**Comment by dah-fari7009** [comment]
Further looking into, the issue occured because `Options.v().set_process_multiple_dex` was set to false. Thank you for your help!
