### ISSUE TITLE
Can FlowDroid distinguish intent extra keys if they are constants?

### ISSUE THREAD

**Issue by RichardHoOoOo** [secure-software-engineering/FlowDroid#481]
Hi @StevenArzt, may I ask can FlowDroid distinguish intent extra keys? After reading the ICCTA paper, it seems FlowDroid is able to do so if keys are constants.

I use the following sample to test. In the example, `MainActivity` puts a source string `wv.getTitle()` in an extra whose key is "b".  `MainActivity2` receives the intent but get `str` from the extra whose key is "a". `str` is finally loaded by the sink method `wv.loadUrl()`.

```
// MainActivity.java
1: Intent intent = new Intent(MainActivity.this, MainActivity2.class);
2: intent.putExtra("b", wv.getTitle());
3: startActivity(intent);

// MainActivity2.java
4: String str = getIntent().getStringExtra("a");
5: wv.loadUrl(str);
```

But when I run FlowDroid with
```
java -jar soot-infoflow-cmd-jar-with-dependencies.jar -a <apk_path> -p <platforms_path> -s <source_sink_path> -im <iccModel_path>
```

It still reported a leak from `wv.getTitle()` to `wv.loadUrl()`, which is obviously wrong.

May I ask are there anything else I need to setup to distinguish intent extra keys?

**Comment by StevenArzt** [comment]
FlowDroid ovder-approximates collections and maps. If one entry in the map is tainted, the entire map is tainted. I have already started on a better model by refactoring the ``AccessPath`` to consist of ``AccessPathFragment``s, which can in turn have a context. However, the context handling itself, e.g., encoding list indices or map keys as contexts, is still open. If you want to contribute, feel free to work something out and open an MR.

**Comment by RichardHoOoOo** [comment]
Hi @StevenArzt,  I see, thanks for your clarification. May I ask a follow-up question?

The [IccTA paper](https://jacquesklein2302.github.io/papers/2015-ICSE-li-iccta.pdf) mentions that `The current version of IccTA performs a simple string analysis to distinguish the extra keys of an Intent between one another` in section IV-A. Since IccTA is integrated into FlowDroid, I thought FlowDroid also supports that feature. 

May I ask is it possible to restore that feature in FlowDroid? If so, I guess I can read the IccTA code to see how they implemented it. Could you give me some suggestions?

**Comment by StevenArzt** [comment]
That's actually two different stories. ICCTA performs an analysis and creates ICC links. These are used to augment the callgraph. The normal flow analysis that runs on this callgraph only passes around ``AccessPath`` objects as part of the ``Abstraction`` and does not distinguish collection elements. So yes, the ICCTA features are all there, but they don't affect taint propagation. I'm not sure if the original paper code from Li Li had some patch for the taint propagation phase, but as I said, the proper way of handling map keys would be to implement context support into the processing of ``AccessPathFragment``s.

**Comment by RichardHoOoOo** [comment]
I got it, thanks for your answer.
