### ISSUE TITLE
Compiling FlowDroid with some modifications

### ISSUE THREAD

**Issue by neupaneprakash** [secure-software-engineering/FlowDroid#485]
Hello @StevenArzt !
I want to build FlowDroid from scratch and come up with some modifications but I am facing issues while compiling the original source code. Is there a specific way for compiling the whole FlowDroid or are there some constraints like there must be some specific java version? 
I would be grateful if you provide me some resources regarding this.
Thank you!

**Comment by StevenArzt** [comment]
You should be able to compile FlowDroid using Maven: ``mvn  package``. If you face issues with the test cases due to, e.g., the Android SDK not being found, disable the tests in Maven: ``mvn package -Dmaven.test.skip=true``.

**Comment by neupaneprakash** [comment]
Thank You Sir!  @StevenArzt
