### ISSUE TITLE
Error while installing FlowDroid 

### ISSUE THREAD

**Issue by PhoenixMallu** [secure-software-engineering/FlowDroid#489]
I am getting an error while installing the latest FlowDroid version on linux 22.04 version.
<img width="1792" alt="Screenshot 2022-06-28 at 5 49 53 PM" src="https://user-images.githubusercontent.com/105406576/176130636-da68e69e-f4cc-4ac7-95e2-22e12c442733.png">

**Comment by StevenArzt** [comment]
That seems to be a specific problem with your local installation.

**Comment by PhoenixMallu** [comment]
I have tried to reinstall FlowDroid, this time I have used the git https copy of the file. I am getting a different error while running the tool using "mvn -DskipTests install". The error is displayed below:
<img width="1792" alt="Screenshot 2022-06-29 at 2 02 32 AM" src="https://user-images.githubusercontent.com/105406576/176233472-2a2baf6d-10ea-457e-82f0-efda4410dd45.png">

**Comment by PhoenixMallu** [comment]
Is there any link detailing the installation process of FlowDroid? it would be a big help for students from other streams to explore the wider applicability of this tool

**Comment by StevenArzt** [comment]
You need to build [Soot](https://github.com/soot-oss/soot) from source first using ``mvn install``. Unfortunately, FlowDroid needs to link against the snapshot version of Soot until Soot has a new proper release.

**Comment by PhoenixMallu** [comment]
I couldn't understand , Can you please specify how we can link the snapshot version of soot and FlowDroid ? The error I have been getting on running  "mvn -DskipTests install" has been overcome by changing the "pom.xml" file inside "soot-inflow" file. The error was caused due to basic feature of maven 3.8.1 which blocked from accessing "http://" site, so I just changed it to "https://" inside pom.xml. The screenshot is given below showing successful running of  "mvn -DskipTests install". 
<img width="1792" alt="Screenshot 2022-06-29 at 5 25 21 PM" src="https://user-images.githubusercontent.com/105406576/176385051-1b952043-adfa-47e4-97c4-76e0a95dc264.png">

**Comment by PhoenixMallu** [comment]
I am still getting error on running full tool installation using "mvn install", the tests are starting but not getting completed and failure to build is being indicated. I think this is due to failure to link soot with Flowdroid, It would be great if you could just help us with the steps involved in linking both (FlowDroid & Soot).
<img width="1792" alt="Screenshot 2022-06-29 at 5 55 49 PM" src="https://user-images.githubusercontent.com/105406576/176389392-b377e0ef-2e91-4411-91d8-45f75ddc171e.png">

**Comment by PhoenixMallu** [comment]
I could successfully build "soot", but still on running the "mvn install" inside FlowDroid , the same error as shown above is coming up. I just put the "soot" folder inside "FlowDroid" folder hoping that automatic linking will happen. Again it narrows down to my question as to how can we link "soot" and "FlowDroid", sorry for sounding like an idiot, I am really fresh in to maven projects and its execution mechanisms. 
<img width="1792" alt="Screenshot 2022-06-29 at 6 23 04 PM" src="https://user-images.githubusercontent.com/105406576/176400048-9d0443e1-a507-4192-95ad-f77cef5184d2.png">

**Comment by StevenArzt** [comment]
Once you have Soot built, run the FlowDroid builds without tests: ``mvn install -DskipTests``

**Comment by PhoenixMallu** [comment]
Then its working... but why am I not able to run the tests?

**Comment by StevenArzt** [comment]
Maybe your configuration is broken, e.g., reference to Android SDK is missing. I went for the easy fix here. Let's if FlowDroid works for you.

**Comment by PhoenixMallu** [comment]
On running mvn -DskipTests install, I am getting this result... I am yet analysing the tool, sorry I am sounding naive

<img width="1792" alt="Screenshot 2022-06-29 at 8 06 07 PM" src="https://user-images.githubusercontent.com/105406576/176416709-e4cf2114-0a26-4396-b1ad-2ff403ae7e24.png">

**Comment by PhoenixMallu** [comment]
> Maybe your configuration is broken, e.g., reference to Android SDK is missing. I went for the easy fix here. Let's if FlowDroid works for you.

My primary aim is to analyse the taint tracking mechanism of Flowdroid and use it test some simple JAVA applications and see how it works, will I be able to do it with this status

**Comment by StevenArzt** [comment]
Your build went fine, soyou should have the FlowDroid command-line JARs in ``soot-infoflow-cmd\target``. Take the JAR with dependencies if you want to start from the command line.

**Comment by PhoenixMallu** [comment]
I was able to run the cmd line tool successfully, can you please suggest me a good reading material which can help me get a better insight about the technicality being FlowDroid. The way it takes in the code, The way it converts it in to byte code and the byte code manipulations carried out for implementing the taint analysis. In short a technical report detailing the coding structure involved in this tool and the role played by each.

**Comment by StevenArzt** [comment]
Have a look at my PhD thesis: https://tuprints.ulb.tu-darmstadt.de/5937/. It covers FlowDroid in detail.

**Comment by PhoenixMallu** [comment]
Thanks Steven ... I could run static taint analysis test on a small ask file namely "Helloworld.apk". using the command given below:
java -jar soot-infoflow-cmd-jar-with-dependencies.jar -a HelloWorld_v1.0_apkpure.com.apk -p platform-tools -s deepak.txt -ac /usr/lib/jvm/jdk1.8.0_331/jre/lib/rt.jar

Irrespective of the application I ran, it shows that there are zero leaks. Is it because of any faulty parameter I am feeding in the command or is it because of error in running of FlowDroid? 

The log obtained on running the test using flowdroid for "Helloworld.apk" is attached below: 
<img width="1792" alt="Screenshot 2022-07-06 at 8 19 49 PM" src="https://user-images.githubusercontent.com/105406576/177533947-a89a9e7a-2a09-4aa4-b0cc-da749c11c852.png">

**Comment by Pokmona1** [comment]
Hola, ejecuto Flowdroid y me aparece compilado sin embargo, no crea archivo flowdroid.jar que puede ser? 
![image](https://github.com/user-attachments/assets/a1f5bc5d-5ab9-4c0a-bec0-73b3119c9afb)
