### ISSUE TITLE
Where can we see the logs for Java tests running inside the sot-info-flow package

### ISSUE THREAD

**Issue by PhoenixMallu** [secure-software-engineering/FlowDroid#504]
Dear Steven

Where can we see the logs generated on running the tests inside the test cases provided inside the soot-info-flow package of FlowDroid.

**Comment by StevenArzt** [comment]
The logs are written to stderr by default, because that's the default behavior of slf4j. You can also provide your own configuration to redirect the output, e.g., by bridging slf4j to log4j as its backend.

**Comment by PhoenixMallu** [comment]
it was due to inability of IntelliJ to load slf4j classes in its class path...once it was added as external dependency the issue was resolved...
