### ISSUE TITLE
mvn install response 503:unavailable

### ISSUE THREAD

**Issue by Myshtea** [secure-software-engineering/FlowDroid#534]
Hello,

I am trying to install the current version of FlowDroid through Maven.

At some point during the install I get a 503 unavailable from one of the ressources, is one of your websites down or is it a problem on my side?

Thank you for your time !

![flowdroid error](https://user-images.githubusercontent.com/51324748/197980328-af19cb07-d28c-4b2f-99fd-248ec16aedb5.png)

**Comment by StevenArzt** [comment]
FlowDroid compiles against the current development version of Soot since we need some of the newer commits. You can build Soot from source (``mvn install``), and then build FlowDroid. I'd suggest to skip the FlowDroid tests during build, as they can be tough to set up correctly.

**Comment by Myshtea** [comment]
Hi @StevenArzt,
Thank you it works perfectly. I'm also really happy to see how much better the current version is compared to the release.
Really good work !
