### ISSUE TITLE
SourcesAndSinks.txt not match

### ISSUE THREAD

**Issue by cjc-github** [secure-software-engineering/FlowDroid#535]
Line does not match some Source Method?

for example, In SourcesAndSinks.txt file

<java.io.File: java.io.File getAbsoluteFile)> -> _SOURCE_

It seem lack the match brackets or some parameter.

**Comment by StevenArzt** [comment]
I have fixed this syntax error. Keep in mind that the source/sink file provided with FlowDroid is only an example for the syntax and that the set of sources and sinks is debatable.

**Comment by cjc-github** [comment]
yeah, i just use part of sources and sinks for data flow analysis.



---Original---
From: "Steven ***@***.***&gt;
Date: Mon, Oct 31, 2022 16:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [secure-software-engineering/FlowDroid] SourcesAndSinks.txt not match (Issue #535)




 
I have fixed this syntax error. Keep in mind that the source/sink file provided with FlowDroid is only an example for the syntax and that the set of sources and sinks is debatable.
