### ISSUE TITLE
What is the termination condition of FlowDroid?

### ISSUE THREAD

**Issue by mmc20520** [secure-software-engineering/FlowDroid#536]
Hi @StevenArzt 

Suppose I have 3 sources (`A`,`B`,`C`) and 3 sinks (`I`, `J`, `K`).

The ground truth leaks are (`A => J`, `B => K`, and `C => K`) and suppose all of them are easy for FlowDroid to find.

Will FlowDroid terminates the analysis if it finds any of the leaks (e.g., `A=>J`) or it finds all of the leaks (e.g., `A => J`, `B => K`, and `C => K`)?

Thanks in advance.

**Comment by StevenArzt** [comment]
FlowDroid will try to find all leaks, unless you specify that it shall stop after N leaks using the configuration. The default is to find all leaks.

**Comment by mmc20520** [comment]
Thanks for your answer.

Have a nice day.
