### ISSUE TITLE
Any way to update AndroidManifest file with a new permission ?

### ISSUE THREAD

**Issue by LouisonGitzinger** [secure-software-engineering/FlowDroid#55]
Hi, 

I'm currently trying to add an Android permission to a given AndroidManifest.xml file in an apk.
I'm using the `ProcessManifest.addPermission` method that add a xml node to the `AxmlNode` manifest but I don't see any way to commit this change to the actual AndroidManifest.xml file.
Is there any helper to do that in FlowDroid or I need to write all the AxmlNode into the file myself ?

Thank you for your help !

**Comment by StevenArzt** [comment]
At the moment, we do not have a means to write the contents of an ProcessManifest object back into a binary XML file on disk. Such a feature would be nice to have, though. Can you try to add code that propagates the changes to the object into the file? That should be an optional feature, though.

**Comment by LouisonGitzinger** [comment]
Ok thanks. Where would be the best place to add such code ? Within the axml package ?
