### ISSUE TITLE
[Question] Creating CFGs from Android APKs

### ISSUE THREAD

**Issue by FrankieYin** [secure-software-engineering/FlowDroid#56]
Dear Developers,  

I'm aware that this question has been asked before and I've read through [#129](https://github.com/secure-software-engineering/soot-infoflow-android/issues/129) and [#155](https://github.com/secure-software-engineering/soot-infoflow-android/issues/155) of soot-infoflow-android but there are still some problems that I encountered while trying to replicate what they did:

1. In @StevenArzt 's answer to #129 as shown below:
```java
public static void main(String[] args) throws IOException, XmlPullParserException {
		// Initialize Soot
		SetupApplication analyzer = new SetupApplication("C:\\Program Files (x86)\\Android\\android-sdk\\platforms",
				"D:/org.fdroid.k9_17046.apk");
		analyzer.getConfig().setTaintAnalysisEnabled(false);
		analyzer.calculateSourcesSinksEntrypoints(Collections.emptySet(), Collections.emptySet());
		analyzer.runInfoflow();
		
		// Iterate over the callgraph
		for (Iterator<Edge> edgeIt = Scene.v().getCallGraph().iterator(); edgeIt.hasNext(); ) {
			Edge edge = edgeIt.next();
			
			SootMethod smSrc = edge.src();
			Unit uSrc = edge.srcStmt();
			SootMethod smDest = edge.tgt();
			
			System.out.println("Edge from " + uSrc + " in " + smSrc + " to " + smDest);
		}
	}
```

The api call to `analyzer.calculateSourcesSinksEntrypoints` has been removed from the current version (I couldn't find any method that has this name in the source apart from it being mentioned in a comment in [SetupApplication.java, line 1022](https://github.com/secure-software-engineering/FlowDroid/blob/master/soot-infoflow-android/src/soot/jimple/infoflow/android/SetupApplication.java#L1022))

2. Similarly, in the code above, the api call to `analyzer.runInfoflow()` no longer works because in the current version this method has at least one parameter.

I'm doing a static analysis on Android APKs which involves creating a CFG of the application (or individual classes). What I would like to get is a directed unit graph representing the CFG. Could you tell me what I should do, using the current version of FlowDroid (v.2.5.1)? If possible, could you kindly put some code sample as well or point me to the sections in the source code where I should be looking at to find my answers?

@StevenArzt 

Best regards,
Zhijun

**Comment by StevenArzt** [comment]
We have greatly simplified the creation of callgraphs in the newer versions of FlowDroid. You can now simply create an instance of the SetupApplication class and then call SetupApplication.constructCallgraph(). After that, you have the callgraph that defines which units call which methods. The following code should work:

```
public static void main(String[] args) throws IOException, XmlPullParserException {
		// Initialize Soot
		SetupApplication analyzer = new SetupApplication("C:\\Program Files (x86)\\Android\\android-sdk\\platforms",
				"D:/org.fdroid.k9_17046.apk");
		analyzer.constructCallgraph();
		
		// Iterate over the callgraph
		for (Iterator<Edge> edgeIt = Scene.v().getCallGraph().iterator(); edgeIt.hasNext(); ) {
			Edge edge = edgeIt.next();
			
			SootMethod smSrc = edge.src();
			Unit uSrc = edge.srcStmt();
			SootMethod smDest = edge.tgt();
			
			System.out.println("Edge from " + uSrc + " in " + smSrc + " to " + smDest);
		}
	}
```

 If you also need the inra-procedural control flow graphs, I suggest to afterwards create an instance of the InfoflowCFG class. This class gives you a unified view over inter-procedural callgraph and intra-procedural control flow graph.

**Comment by FrankieYin** [comment]
Hi @StevenArzt ,

Thank you for the quick reply! 
Yes I do need the ICFGs. Do you mean after calling `analyzer.constructcallgraph()`, when I create an InfoflowCFG instance, all the information about successor and predecessor of statements and the caller/callee relationships will be already stored in that instance?

Also I saw the code in [#155](https://github.com/secure-software-engineering/soot-infoflow-android/issues/155) by @ehsan-is-everything as shown below:
```java
```

**Comment by AbdulAli** [comment]
Hi @FrankieYin 
Did you figure out what to pass on this method?

Regards.
Ali
