### ISSUE TITLE
Source and sink definition of methods in the MainActivity.java class

### ISSUE THREAD

**Issue by NicolasFNino** [secure-software-engineering/FlowDroid#560]
I wanted to ask if the methods inside the MainActivity class of an apk are not supposed to be defined as a source or a sink. This is because during the taint analysis these types of methods are never recognized as such, despite being declared in the sourcessinks.xml file. Meanwhile, a method in any other class is correctly identified as a source or a sink depending on the xml file definition. 

Thank you.

**Comment by StevenArzt** [comment]
You can declare any method as source or sink, regardless of the class in which it is defined. If your method signature is correct in the source/sink definition file, that should work.

App-specific sources or sinks are rather uncommon, though. Most people declare Android API methods as sources or sinks.

**Comment by NicolasFNino** [comment]
Thank you so much for your response. 

My follow-up question now is, how would I define the source signature definition of a constructor, when i am interested in one of the parameters used, as an example: 

`public class Test {
    public Test(int, String) {
        ....
    }
}`

The value I'm interested in is the second parameter of type String. This is what I am thinking:

`<method signature="&lt;com.test.Test: void &lt;init&gt;(int, java.lang.String)&gt;">  `
`        <param index="1" type="java.lang.String">  `
`                <accessPath isSource="true" isSink="false"/>  `
`        </param> ` 
`</method>`

But it does not seem to work. 

Thank you so much for taking the time to look at this.

**Comment by NicolasFNino** [comment]
Also, can you please help me understand what is wrong with these signatures? Flowdroid cannot recognize the methods as source or sink.

The code:
![image](https://user-images.githubusercontent.com/92283708/208215489-8903858c-f96c-45bf-9625-0cbe4f6f7db5.png)

SinksAndSources.txt:
![image](https://user-images.githubusercontent.com/92283708/208215557-d2923630-ad3d-48db-9bd5-509ff180b24d.png)


Thanks a lot!
