### ISSUE TITLE
Creating call graph with different SourceAndSinks.txt

### ISSUE THREAD

**Issue by sharboda** [secure-software-engineering/FlowDroid#58]
Hi Steven,

I've been trying to create the call graph with a modified sourcesAndSinks file. I followed the below process. However, the generated call graph still contains the nodes from the original sourcesAndSinks file. Could you please let me know if I'm missing something?

InfoflowAndroidConfiguration config = new InfoflowAndroidConfiguration();
config.setIgnoreFlowsInSystemPackages(true);
AnalysisFileConfiguration fileConfig = new AnalysisFileConfiguration();
fileConfig.setAndroidPlatformDir("C:\\Android\\android-sdk\\platforms");
fileConfig.setSourceSinkFile("D:\\CMU\\Capstone\\SourcesAndSinks.txt");
fileConfig.setTargetAPKFile("D:\\CMU\\Capstone\\*****.apk");
config.getAnalysisFileConfig().merge(fileConfig);
SetupApplication app = new SetupApplication(config);

app.constructCallgraph();
CallGraph appCallGraph = Scene.v().getCallGraph();

Thank you,
Sharada

**Comment by StevenArzt** [comment]
A call graph is independent from the sources and sinks. A call grap only denotes which units in the code calls which methods. The sources and sinks are only relevant for the data flow analysis that is later on conducted on the interprocedural control flow graph built on top of the callgraph.
