### ISSUE TITLE
Where can I find the older version of 1.5.1?

### ISSUE THREAD

**Issue by fwt1888** [secure-software-engineering/FlowDroid#585]
Hello! 
Recently I wanted to test another project susi to generate the sources and sinks of the apk files, but I found that the location of many of functions is different from the new version.

So I asked chatgpt to know what is the version of flowdroid corresponding to susi?
It told me that the match is version 1.5.1 released in 2016.

However, it cannot be downloaded on github, where can I get it?

**Comment by StevenArzt** [comment]
@JordanSamhi should have a version that works.

**Comment by JordanSamhi** [comment]
Hi @fwt1888,

Please have a look here: https://github.com/JordanSamhi/CoDoC/tree/master/artefacts/SuSi/launch_SuSi

Let me know if you need anything else.

**Comment by fwt1888** [comment]
Thanks for your replies, it's very helpful for me
