### ISSUE TITLE
Previous Version FlowDroid Jar Apply

### ISSUE THREAD

**Issue by MoranLian** [secure-software-engineering/FlowDroid#615]
Hello Steven,

I really appreciate your fantastic contribution to FlowDroid, which facilitates Android program analysis.

Recently, I had to build an older project to evaluate my paper. Unfortunately, the old project requires a previous version of the jar library for soot-infoflow and soot-infoflow-android. I have tried all the solutions I can think of, but they have all been in vain.

Could you please share the previous version (maybe released in 2016 or 2015) jar files with me? If Github is not appropriate, email is also okay for me (my email is morangeous@gmail.com). Any help will be appreciated.

Thank you so much.

Moran

**Comment by StevenArzt** [comment]
Hello Moran,

You can download the old release JARs from the [Github release page](https://github.com/secure-software-engineering/FlowDroid/releases). If you're looking for really old releases, e.g., from 2015 or 2016, I don't think we have them anymore. There used to be separate repositories for ``soot-infoflow``, ``soot-infoflow-android``, etc., but we replaced them with an integrated ``FlowDroid`` repository at some point and deleted the old ones. Maybe you can still find some unofficial clones of the old repositories, though.

Best regards,
  Steven

**Comment by MoranLian** [comment]
Hi Steven,

Really thanks for your kind help, I am looking for the older one in other unofficial repos.

Best regards,
Moran
