### ISSUE TITLE
Some artifacts of version 2.11.0 and 2.11.1 in Maven Central are defect

### ISSUE THREAD

**Issue by jpstotz** [secure-software-engineering/FlowDroid#619]
Affected for example:

        <dependency>
            <groupId>de.fraunhofer.sit.sse.flowdroid</groupId>
            <artifactId>soot-infoflow-android</artifactId>
            <version>2.11.1</version>
        </dependency>

If you add this dependency to a Maven project the artifact and pom are downloaded but can not be used.
You get errors like:

    Could not find artifact de.fraunhofer.sit.sse.flowdroid:parent:pom:2.11.1 in central (https://repo.maven.apache.org/maven2)

**Comment by StevenArzt** [comment]
The parent POM indeed seems to be missing from Maven central. Since we should do a new release anyway, I'd see we fix this in the new release instead of trying to somehow upload the parent POM for the old release.

**Comment by ym-xie** [comment]
Has this problem been solved now?

**Comment by StevenArzt** [comment]
FlowDroid version 2.12 has been released and also contains the parent POM: https://central.sonatype.com/namespace/de.fraunhofer.sit.sse.flowdroid
