### ISSUE TITLE
Entry Point

### ISSUE THREAD

**Issue by juLialily** [secure-software-engineering/FlowDroid#629]
Hi, i'm trying to analyze a Java program with Flowdroid. Until now, i have used `DefaultEntryPointCreator`. I have defined like this `<packagename.classname: void main(java.lang.String[])>` . But i want to implement to find class automatically without defining class name. Is there any way to automatically find entry point?

**Comment by StevenArzt** [comment]
We don't have that yet. There may be multiple classes with ``main`` methods in your Java program. You could implement logic that assumes that there is only such class, which might work for at least some program. You can also parse the JARs manifest to check whether it defines a main class (that's what our commercial code scanner does).

**Comment by juLialily** [comment]
Thanks for your reply:)
