### ISSUE TITLE
[Solved] How to get a standard output(i.e. xml or json) if I am using cmd-line tools for tracking data flow? 

### ISSUE THREAD

**Issue by likaikoplee** [secure-software-engineering/FlowDroid#63]
Hi, 
I am wondering if use below command-line tools to get a data flow tracker, How could I get a standard output for the data leakage, like xml or json:
If you want to use the command-line tool to run the data flow tracker, you can use the following command:

`java -jar soot-infoflow-cmd/target/soot-infoflow-cmd-jar-with-dependencies.jar \
    -a <APK File> \
    -p <Android JAR folder> \
    -s <SourcesSinks file> \
    --timeout 1000 \
    --resulttimeout 1000 (Both params limits the runing of a task)
`

What I can get is the log output of the running programme. There might be some scan results in it. But most of them are the process log of it . 
When the cmd finished, I get a directory, but without anything in it.
Could you guys please explain it a bit for me?
   ###Thanks.

**Comment by StevenArzt** [comment]
There is a -o option in the command line application for generating an XML output file with all the data flows that have been discovered.
