### ISSUE TITLE
Error in install progress

### ISSUE THREAD

**Issue by hannuri-k** [secure-software-engineering/FlowDroid#632]
When I type 'mvn install' inside the FlowDroid folder, I get the following error. How can I fix it? java is version 20.

<img width="824" alt="스크린샷 2023-07-11 오후 1 58 40" src="https://github.com/secure-software-engineering/FlowDroid/assets/138416076/26c71e36-13b9-4dec-a095-ea370ac290b3">

The screenshot below shows the inside of the pom.xml file
<img width="818" alt="스크린샷 2023-07-11 오후 2 00 10" src="https://github.com/secure-software-engineering/FlowDroid/assets/138416076/76aec2c0-5c8a-4cdb-8cf4-543b8789b39a">

**Comment by t1mlange** [comment]
I'd suggest you to run a single test and look whether it displays some error message while running.

**Comment by StevenArzt** [comment]
The tests reference the ``rt.jar`` file that only existed up to Java 9. We check whether FlowDroid finds flows inside the Java standard library, but the test suite was never ported to the new Java module file system. I assume that you only have Java 20 on your machine. The tests therefore find no code to analyze.

I suggest that you either use the official FlowDroid JARs from Maven Central (release version 1.12 is fairly recent), or that you build FlowDroid and skip the tests using ``mvn install -DskipTests``.

We run the tests as part of our CI/CD pipeline on a machine that has Java 8 installed on the side for the ``rt.jar``. FlowDroid itself obviously runs on modern Java as well, it's just a problem with the tests.

**Comment by hannuri-k** [comment]
Failure occurred at the StubDroid stage when 'mvn install -DskipTests' was used. Even in this case, can I just assume that there is no problem and proceed? Or do I need to install the Java 8 version?

**Comment by StevenArzt** [comment]
Which failure? Please be more precise.

**Comment by hannuri-k** [comment]
<img width="577" alt="스크린샷 2023-07-13 오전 10 03 54" src="https://github.com/secure-software-engineering/FlowDroid/assets/138416076/96dcc017-5d50-4c3b-92af-35e156aeaa4d">

**Comment by StevenArzt** [comment]
I just committed a fix that should resolve this issue. Apparently, the "attached" goal in the Maven assembly plugin has been removed in newer versions.

**Comment by hannuri-k** [comment]
<img width="1297" alt="스크린샷 2023-07-18 오전 11 36 33" src="https://github.com/secure-software-engineering/FlowDroid/assets/138416076/e38eeefe-1148-46ab-9f50-ee74cab2f5eb">
Hi, I solved the last problem but got a new error. When I rebuilt after deleting the folder, it succeeds up to the 'stubdroid' step but fails at the 'FlowDroid Command Line Util' step. I used the command 'mvn install -DskipTests'.

**Comment by StevenArzt** [comment]
That's interesting. I don't really know why this fails, see screenshot below:

![image](https://github.com/secure-software-engineering/FlowDroid/assets/2691304/5e27cb36-83c9-4ef9-964c-705230368533)

**Comment by hannuri-k** [comment]
<img width="853" alt="스크린샷 2023-07-19 오후 12 15 50" src="https://github.com/secure-software-engineering/FlowDroid/assets/138416076/45a2dace-1ba4-462f-99a1-bac31afb2ddb">
The java version is the same as your screenshot, and the mvn version looks like the below image. 

The pom file in the root folder 
<img width="674" alt="스크린샷 2023-07-19 오후 12 19 57" src="https://github.com/secure-software-engineering/FlowDroid/assets/138416076/43d9de86-4b3a-4e04-9964-1056332e683e">
<img width="1436" alt="스크린샷 2023-07-19 오후 12 20 10" src="https://github.com/secure-software-engineering/FlowDroid/assets/138416076/a7291ec3-d65a-427f-80bb-e10904c15a0c">

I did not modify the pom files in the subfolders.
Do I need to modify the pom file?
