### ISSUE TITLE
Can't build the latest FlowDroid 2.6 SNAPSHOT

### ISSUE THREAD

**Issue by zhanghan177** [secure-software-engineering/FlowDroid#66]
I tried to build by `mvn install` the latest 2.6 SNAPSHOT from both develop and master branches. They both failed. 

The error message is 
> [INFO] Reactor Summary:
> [INFO]
> [INFO] soot-infoflow ...................................... FAILURE [ 20.968 s]
> [INFO] soot-infoflow-android .............................. SKIPPED
> [INFO] StubDroid .......................................... SKIPPED
> [INFO] FlowDroid Command Line Util ........................ SKIPPED
> [INFO] FlowDroid Parent Module ............................ SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 21.184 s
> [INFO] Finished at: 2018-09-06T22:02:18Z
> [INFO] Final Memory: 25M/267M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project soot-infoflow: Compilation failure
> [ERROR] /home/hanzhang/FlowDroid/soot-infoflow/src/soot/jimple/infoflow/solver/fastSolver/InfoflowSolver.java:[117,37] cannot find symbol
> [ERROR]   symbol:   method invalidate()
> [ERROR]   location: variable ffCache of type heros.FlowFunctionCache<N,D,soot.SootMethod>
> [ERROR]
> [ERROR] -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

It looks like @StevenArzt added an invalidate() method to Heros (https://github.com/Sable/heros/commit/c740e6b4c80ab9e6162a39dcc280b22429e0279b) fairly recently (15 days ago). 

During `mvn install`, it tries to retrieve Heros-1.0.1-SNAPSHOT from soot-release (https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-release/heros/heros/1.0.1-SNAPSHOT) and soot-snapshot (https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/heros/heros/1.0.1-SNAPSHOT). 

From soot-snapshot, the latest Heros-1.0.1-SNAPSHOT is from April (https://soot-build.cs.uni-paderborn.de/nexus/#browse/browse/components:soot-snapshot:36e3dec8de528c9b26d8dfec9104f3e7), which doesn't reflect the change. As this log message shows:
> Downloading from soot-snapshot: https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/heros/heros/1.0.1-SNAPSHOT/heros-1.0.1-20180418.125229-1.pom

From soot-release, I received the error message as
> [WARNING] Could not transfer metadata heros:heros:1.0.1-SNAPSHOT/maven-metadata.xml from/to soot-release (https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-release/): Failed to transfer file: https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-release/heros/heros/1.0.1-SNAPSHOT/maven-metadata.xml. Return code is: 400 , ReasonPhrase:Repository version policy: RELEASE does not allow metadata in path: heros/heros/1.0.1-SNAPSHOT/maven-metadata.xml.

Would there be any suggestions on how to fix this error?

**Comment by StevenArzt** [comment]
Apparently, the build server for Heros is broken. The best possibility for a quick fix would be to check out Heros from git and build it locally. Using "mvn install", you should get a copy in your local Maven cache and there should not be any need for Maven to download it anymore.

@mbenz89 Can you please have a look whether we have a working build system for Heros at the moment and whether the Heros artifacts are correctly uploaded to the Nexus repository?

**Comment by mbenz89** [comment]
Everything should be up and working again. Thanks for reporting!

**Comment by StevenArzt** [comment]
Thanks for the fix, Manuel!

**Comment by zhanghan177** [comment]
Thanks the issue is now fixed.
