### ISSUE TITLE
README outdated wrt. to standalone cmd jar

### ISSUE THREAD

**Issue by mal-tee** [secure-software-engineering/FlowDroid#688]
The readme states:

> If you only want to use the command-line tool, all you need is the "soot-infoflow-cmd-jar-with-dependencies.jar" file.

But this jar doesn't seem to be available anymore, since the move to maven and the ditch of GH releases. I've tried to use the `soot-infoflow-cmd-2.12.0.jar` in my `.m2` folder as a standalone just for fun, but its missing some dependencies.

**Comment by StevenArzt** [comment]
You can try to compile FlowDroid on your own:

```
mvn package -DskipTests
```
