### ISSUE TITLE
android.app.Activity is marked as application class

### ISSUE THREAD

**Issue by mbenz89** [secure-software-engineering/FlowDroid#72]
HI Steven.

I wonder why you set `android.app.Activity` as application class in the [LibraryClassPatcher](https://github.com/secure-software-engineering/FlowDroid/blob/a1804e130acebf655762f2e8f9477d3e1217a0e6/soot-infoflow/src/soot/jimple/infoflow/cfg/LibraryClassPatcher.java#L678).
This messes with my post analysis and I am curious if and why this is necessary? Especially, because you mark it as library class in a [previously called patch](https://github.com/secure-software-engineering/FlowDroid/blob/a1804e130acebf655762f2e8f9477d3e1217a0e6/soot-infoflow/src/soot/jimple/infoflow/cfg/LibraryClassPatcher.java#L270).

Is it safe to change this to `setLibraryClass` as well, or am I better of doing this before/after FlowDroid runs?

**Comment by StevenArzt** [comment]
Hi Manuel,

That looks like a good old bug. I don't see any reason to make this class an application class. Feel free to change it, and please open up a merge request.
