### ISSUE TITLE
Can not run project with FlowDroid

### ISSUE THREAD

**Issue by RabbitDong-on** [secure-software-engineering/FlowDroid#723]
I add Flowdroid via Maven like below.

<dependency>
        <groupId>de.fraunhofer.sit.sse.flowdroid</groupId>
        <artifactId>soot-infoflow</artifactId>
        <version>2.12.0</version>
    </dependency>
    <dependency>
        <groupId>de.fraunhofer.sit.sse.flowdroid</groupId>
        <artifactId>soot-infoflow-summaries</artifactId>
        <version>2.12.0</version>
    </dependency>
    <dependency>
        <groupId>de.fraunhofer.sit.sse.flowdroid</groupId>
        <artifactId>soot-infoflow-android</artifactId>
        <version>2.12.0</version>
    </dependency>

I can compile project, but can not run.
I get the following information in the shell.
Error: Unable to initialize main class taintanalysis.STA
Caused by: java.lang.NoClassDefFoundError: soot/jimple/infoflow/config/IInfoflowConfig

Please help me slove this problem. thanks.

**Comment by StevenArzt** [comment]
Can you provide a link to the full project? We integrate FlowDroid via Maven in various projects and it normally works just fine.

**Comment by RabbitDong-on** [comment]
Thanks for your reply.
Recently, i am studing the flowdroid.
I try to run this project(https://github.com/dorawyy/flowdroid_tutorial).
I modified the version of flowdroid in the pom.xml.

**Comment by RabbitDong-on** [comment]
the code is in the master branch.

**Comment by RabbitDong-on** [comment]
Env: Maven 3.6.0; Java 8

**Comment by RabbitDong-on** [comment]
Could you provide some advises to solve this problem? thanks

**Comment by RabbitDong-on** [comment]
This problem is fixed. The root cause is from misconfiguration.

**Comment by StevenArzt** [comment]
ok, great to hear that. Sorry for not replying, I was quite busy. You might have seen that we have released a new FlowDroid version and since then, we have also worked on the next improvements.

**Comment by RabbitDong-on** [comment]
Hi, Steven. cloud you provide some suggestions on #724
