### ISSUE TITLE
About flowdroid running memory usage settings

### ISSUE THREAD

**Issue by KyleLeith-007** [secure-software-engineering/FlowDroid#740]
I am studying the source code of flowdroid. I have run the analysis program through the source code and found that memory is not enough in many cases. I have not found the parameters related to memory in the configuration parameters of flowdroid. How can I adjust it?
Specifically, I want to modify the maximum memory of the following logs output by flowdroid: [main] info root.jimple.infoflow.memory MemoryWarningSystem - Registered a memory warning system for 2,436.3 MiB
Thanks in advance.

**Comment by StevenArzt** [comment]
You can use the ``-Xmx`` VM parameter to specify the maximum heap memory for the JVM: https://docs.oracle.com/cd/E19159-01/819-3681/abeik/index.html

**Comment by KyleLeith-007** [comment]
> You can use the `-Xmx` VM parameter to specify the maximum heap memory for the JVM: https://docs.oracle.com/cd/E19159-01/819-3681/abeik/index.html
Thank you very much for your answer. I have solved the problem as you said.
