### ISSUE TITLE
How could I get a leak result's line number? 

### ISSUE THREAD

**Issue by likaikoplee** [secure-software-engineering/FlowDroid#76]
Hi, 
I am using Flowdroid cmd-line tools to scan the app. The params are as follows:
```
/**
     * Sample command
     * [java -jar ./libs/soot-infoflow-cmd-jar-with-dependencies.jar
     * -a sample.apk
     * -p android.jar
     * -s SourcesAndSinks.txt
     * --aliasflowins
     * --aplength 1
     * --noexceptions
     * --nostatic
     * --timeout 300
     * --resulttimeout 300
     * --output xxx
     * **/
```
One of the results is as follows:
`
<Result>
            <Sink Statement="virtualinvoke $r1.&lt;java.net.Socket: void connect(java.net.SocketAddress)&gt;($r2)">
                <AccessPath Value="$r2" Type="java.net.InetSocketAddress" TaintSubFields="true">
                    <Fields>
                        <Field Value="&lt;java.net.InetSocketAddress: int port&gt;" Type="int"></Field>
                    </Fields>
                </AccessPath>
            </Sink>
            <Sources>
                <Source Statement="$r1 = interfaceinvoke $r6.&lt;android.database.Cursor: java.lang.String getString(int)&gt;(0)">
                    <AccessPath Value="$r1" Type="java.lang.String" TaintSubFields="true"></AccessPath>
                </Source>
            </Sources>
        </Result>
`

I am wondering if there is a parameter to get the line number of the leak in the result? I read the document and found nothing.
Thanks

**Comment by StevenArzt** [comment]
At the moment, we do not write the line numbers into the output XML file. However, this should be a fairly simple extension to class ```InfoflowResultsSerializer```. You can simply call ```getJavaSourceStartLineNumber()``` on the statements. If you choose to integrate this feature, can you please share your code by creating a merge request to the develop branch?

**Comment by StevenArzt** [comment]
We have a merge request for it, so I'll close this issue as done.
