### ISSUE TITLE
class file has wrong version 61.0

### ISSUE THREAD

**Issue by Zzzzzack2** [secure-software-engineering/FlowDroid#773]
Why there is a error while using the flowdroid downloaded from maven
**[Class file has wrong version 61.0, should be 52.0](https://stackoverflow.com/questions/76031419/class-file-has-wrong-version-61-0-should-be-52-0)**

**Comment by StevenArzt** [comment]
You are trying to use FlowDroid without an outdated Java version. FlowDroid now requires at least Java 17. You are trying with Java 8, which is no longer supported.
