### ISSUE TITLE
Some errors about scene.makeMethodRef in file AbstractInfoflow.java

### ISSUE THREAD

**Issue by WhiteSeele** [secure-software-engineering/FlowDroid#778]
Dear FlowDroid Developers,
I get the develop branch and build it in IDEA with maven. However I failed to build it and IDEA gives me some errors in AbstractInfoflow.java about the usage of the call scene.makeMethodRef:
```
SootMethodRef appendObjectRef = scene.makeMethodRef(scStringBuilder,
				"java.lang.StringBuilder append(java.lang.Object)", false);
```
This method needs five parameters: `soot.SootClass,java.lang.String,java.util.List<soot.Type>,soot.Type,boolean`, however in this file all the calls about this method is only provided three parameters: `soot.SootClass,java.lang.String,boolean`. So the build fails. 

Is this a bug ? Or is it an issue with my JDK or Soot version?

![屏幕截图 2024-11-05 103756](https://github.com/user-attachments/assets/f1dfd589-2651-4e4f-bddd-a3ee79f052b9)

**Comment by WhiteSeele** [comment]
Well，I found that in Soot's github repository now，the definition of this method exists：
![屏幕截图 2024-11-05 125632](https://github.com/user-attachments/assets/454d7aa6-5b89-4130-8756-d583daa74238)

However，the newest release about the Soot doesn't have it ! I think this is the reason that I can't successfully build my project.
![屏幕截图 2024-11-05 125823](https://github.com/user-attachments/assets/2bcfe950-18f5-4955-980c-285ab6b7e4c9)

**Comment by StevenArzt** [comment]
Please ensure that you use compatible versions of Soot and FlowDroid. FlowDroid is a Maven project and the ``pom.xml`` file defines its dependencies. I'm not an expert with IDEA, but many IDEs allow you to import a project as a Maven project. It will then ensure that all dependencies are resolved correctly.

If you import Soot manually, you need to check the ``pom.xml``. The FlowDroid release versions always depend on Soot release versions, but FlowDroid development versions may depend on Soot development versions, i.e., snapshots. You cannot rely on the FlowDroid development version to work with the last Soot release as development may already have progeressed beyond the latest Soot release.

**Comment by WhiteSeele** [comment]
> Please ensure that you use compatible versions of Soot and FlowDroid. FlowDroid is a Maven project and the `pom.xml` file defines its dependencies. I'm not an expert with IDEA, but many IDEs allow you to import a project as a Maven project. It will then ensure that all dependencies are resolved correctly.
> 
> If you import Soot manually, you need to check the `pom.xml`. The FlowDroid release versions always depend on Soot release versions, but FlowDroid development versions may depend on Soot development versions, i.e., snapshots. You cannot rely on the FlowDroid development version to work with the last Soot release as development may already have progeressed beyond the latest Soot release.

Thanks for replying！Actually that is the problem. FlowDroid development uses the API with Soot development 4.7-snapshots version, however in it's pom.xml file it still refer the Soot 4.6-snapshots version, which is not modified about this definition of the method. When I changed the Soot version, it works normally. Thank you !
