### ISSUE TITLE
Soot wrongly repacks these two apks

### ISSUE THREAD

**Issue by LouisonGitzinger** [secure-software-engineering/FlowDroid#78]
Hello @StevenArzt,

I posted an issue on the Soot repo a month ago about two apks that are crashing when unpacked/repackaged by soot [here](https://github.com/Sable/soot/issues/999).

To investigate that, I first translated the original and repackaged dex files and then compared them (see my last comment on the soot issue).
I found out that Soot made a mistake by creating a wrong cast operation on the repackaged dex file.

I would like to investigate this bug further, do you have an idea of where and how I should start ?

Thank you very much for your help.

Louison

**Comment by StevenArzt** [comment]
Hi Louison,

Let me comment on this in the Soot repository, not here. Therefore, I'll close this issue.

Best regards,
  Steven
