### ISSUE TITLE
There is an error in the method summary

### ISSUE THREAD

**Issue by litter47** [secure-software-engineering/FlowDroid#788]
In soot-infoflow-summaries/summariesManual/javax.servlet.ServletRequest.xml
`			<clears>
				<clear sourceSinkType="Field"
					   AccessPath="[[javax.servlet.ServletRequest: java.lang.Object[] attributes]"
					   AccessPathTypes="[java.lang.Object[]]"
					   constrained="true" />
			</clears>
`
AccessPath There is one more [

**Comment by StevenArzt** [comment]
Thank you for reporting the issue.
