### ISSUE TITLE
Error 400 on Nexus repo when trying to build FlowDroid with maven

### ISSUE THREAD

**Issue by LouisonGitzinger** [secure-software-engineering/FlowDroid#8]
Hi again, 

I'm trying to build FlowDroid from scratch with maven following instructions from the REAMDE.
It seems that something goes wrong when Maven tries to download some dependencies, it throws an Error 400 : 
```
Return code is: 400 , ReasonPhrase:Repository version policy: RELEASE does not allow metadata in path: heros/heros/0.0.1-SNAPSHOT/maven-metadata.xml.
```
Something wring on Nexus side ?

**Comment by StevenArzt** [comment]
Apparently, the nexus repository was changed to only support the release versions. In the develop branch, I have changed the POM files to reference the 1.0.0 version of Heros instead.
