### ISSUE TITLE
Returning `results` instead of output with logger

### ISSUE THREAD

**Issue by huchenlei** [secure-software-engineering/FlowDroid#89]
Noticed that `soot.jimple.infoflow.Infoflow.runAnalysis` current has no return value. Instead, the analysis result got output to either console or file with the program logger. It could be quite inconvenient for developer who would like to use soot-infoflow as an external library.

**Comment by StevenArzt** [comment]
The ```runInfoflow()``` method is not public API. There are two overloads, one of which is private, and one of which is protected. Please use the public method ```computeInfoflow()``` instead. After the data flow computation has finished, you can call ```getResults()``` to obtain the results via the API.
