### ISSUE TITLE
Result Serialization ICFG always null

### ISSUE THREAD

**Issue by ClaudioRizzo** [secure-software-engineering/FlowDroid#9]
Hi, I noticed that when reporting FlowDroid results in SetupApplication.java in runInfoflow() method (towards the end), the ICFG gets always set to null by resultAggregator.clearLastResults() before calling serializeResults(resultAggregator.getAggregatedResults(), resultAggregator.getLastICFG()).

It results in an xml output with less information (for example you can't get the method attribute)

**Comment by StevenArzt** [comment]
Thanks for finding that out. Can you open a merge request with a proposed fix?
