### ISSUE TITLE
how to make IR(jimple) about the apk as FlowDroid's input?

### ISSUE THREAD

**Issue by android4studies** [secure-software-engineering/FlowDroid#90]
Here Sir, For your idea about FlowDroid, I feel so surprised that I have some questions about its implementation.

Q1: Can I replace Android apk with apk's Jimple as its input?
Q2: If not, where can I do some modifications to make Q1 realized?If yes, Can you tell me how?

Thanks for your reply ：)

**Comment by StevenArzt** [comment]
FlowDroid does not support Jimple files as inputs at the moment. You can try to change the ```SetupApplication```, method ```initializeSoot()``` to add such support.
