### ISSUE TITLE
link button listener to button's activity in call graph

### ISSUE THREAD

**Issue by mikesxf** [secure-software-engineering/FlowDroid#97]
Hello, sir. Recently, I am using Flowdroid to construct the call graph, with IC3 to solve ICC problems. However, I can't link the callback listerner (such as `MyListener.onClick()`) to where it is registered (such as `setOnClickListener(new MyListener(this))` in `OnCreate()` of MainActivity)
For example:
`public class MainActivity extends Activity {`
`    protected void onCreate(Bundle savedInstanceState) {`
`        ...`
`        Button b = findViewById(R.id.button);`
`        b.setOnClickListener(new MyListener());`
`    }`
`}`
`public class MyListener implements View.OnClickListener {`
`         @Override`
`          public void onClick(View v) {`
`          ...`
`      }`
`}`
result: MyListener: OnClick() called by MainActivity OnCreate()
I wonder whether Flowdroid or IC3 can solve the problem？and how? Thanks a lot!

**Comment by jyotigajrani** [comment]
@mikesxf : Have you solved the problem?
If yes, Please tell how.

**Comment by mikesxf** [comment]
> @mikesxf : Have you solved the problem?
> If yes, Please tell how.

To some extent, I think yes. I use the intermediate result when constructing the CG. It contains the relation between `MainActivity` and `MyListener:OnClick()`. **However**, I'm not sure whether it contains all such relations and it can't locate the method `OnCreate()` in `MainActivity`. But it may be enough for me and I didn't go on although I think I can indeed locate the method `OnCreate()`.
