### ISSUE TITLE
Add custom rules

### ISSUE THREAD

**Issue by elie-cst** [secure-software-engineering/FlowDroid#98]
Hello,
Is it possible to add specific tags based on custom rules like "Sink", "Source", "Neither" and "Both"? For example, I would like to insert an SMS tag when detecting an SMS leak.
Thanks in advance.

**Comment by StevenArzt** [comment]
You can add categories to sources and sinks, or you can create your own implementation of the ```ISourceSinkManager``` interface, which fills the ```userData```field of the ```SourceInfo``` object.
